// Firebase configuration template
// Auto-generated by Mobigen Firebase Connector

import type { CodeGenContext } from '@mobigen/connectors/core';

export function firebaseConfigTemplate(ctx: CodeGenContext): string {
  return `/**
 * Firebase Configuration
 * Auto-generated for ${ctx.projectConfig.appName}
 * Generated: ${new Date().toISOString()}
 *
 * This file initializes Firebase with your project credentials.
 * Do not commit this file with production credentials.
 */

import { FirebaseApp, initializeApp } from '@react-native-firebase/app';
import auth from '@react-native-firebase/auth';
import firestore from '@react-native-firebase/firestore';
import storage from '@react-native-firebase/storage';

// Firebase configuration
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || '${ctx.credentials.apiKey}',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || '${ctx.credentials.authDomain}',
  projectId: process.env.FIREBASE_PROJECT_ID || '${ctx.credentials.projectId}',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || '${ctx.credentials.storageBucket}',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '${ctx.credentials.messagingSenderId}',
  appId: process.env.FIREBASE_APP_ID || '${ctx.credentials.appId}',
};

let firebaseApp: FirebaseApp | null = null;

/**
 * Initialize Firebase
 * Call this once when your app starts
 */
export async function initializeFirebase(): Promise<void> {
  if (firebaseApp) {
    console.log('[Firebase] Already initialized');
    return;
  }

  try {
    firebaseApp = await initializeApp(firebaseConfig);
    console.log('[Firebase] Initialized successfully');

    // Enable offline persistence for Firestore
    await firestore().settings({
      persistence: true,
      cacheSizeBytes: firestore.CACHE_SIZE_UNLIMITED,
    });

    console.log('[Firebase] Firestore offline persistence enabled');
  } catch (error) {
    console.error('[Firebase] Initialization failed:', error);
    throw error;
  }
}

/**
 * Get Firebase app instance
 */
export function getFirebaseApp(): FirebaseApp {
  if (!firebaseApp) {
    throw new Error('Firebase not initialized. Call initializeFirebase() first.');
  }
  return firebaseApp;
}

/**
 * Get Firebase Auth instance
 */
export function getAuth() {
  return auth();
}

/**
 * Get Firestore instance
 */
export function getFirestore() {
  return firestore();
}

/**
 * Get Storage instance
 */
export function getStorage() {
  return storage();
}

// Export services
export { auth, firestore, storage };
`;
}
