// Firebase Auth service template
// Auto-generated by Mobigen Firebase Connector

import type { CodeGenContext } from '@mobigen/connectors/core';

export function firebaseAuthTemplate(ctx: CodeGenContext): string {
  return `/**
 * Firebase Authentication Service
 * Auto-generated for ${ctx.projectConfig.appName}
 *
 * Provides authentication methods for email/password, Google, and Apple Sign-In.
 * Includes offline support and error handling.
 */

import auth, { FirebaseAuthTypes } from '@react-native-firebase/auth';
import { GoogleSignin } from '@react-native-google-signin/google-signin';
import { appleAuth } from '@invertase/react-native-apple-authentication';
import type { FirebaseUser, AuthError } from '../types/firebase';

// Configure Google Sign-In (iOS)
GoogleSignin.configure({
  webClientId: process.env.FIREBASE_WEB_CLIENT_ID,
});

/**
 * Sign in with email and password
 */
export async function signInWithEmail(
  email: string,
  password: string
): Promise<{ user: FirebaseUser | null; error?: AuthError }> {
  try {
    const userCredential = await auth().signInWithEmailAndPassword(email, password);
    return {
      user: mapFirebaseUser(userCredential.user),
    };
  } catch (error: any) {
    return {
      user: null,
      error: mapAuthError(error),
    };
  }
}

/**
 * Sign up with email and password
 */
export async function signUpWithEmail(
  email: string,
  password: string,
  displayName?: string
): Promise<{ user: FirebaseUser | null; error?: AuthError }> {
  try {
    const userCredential = await auth().createUserWithEmailAndPassword(email, password);

    // Update display name if provided
    if (displayName && userCredential.user) {
      await userCredential.user.updateProfile({ displayName });
    }

    return {
      user: mapFirebaseUser(userCredential.user),
    };
  } catch (error: any) {
    return {
      user: null,
      error: mapAuthError(error),
    };
  }
}

/**
 * Sign in with Google
 */
export async function signInWithGoogle(): Promise<{
  user: FirebaseUser | null;
  error?: AuthError;
}> {
  try {
    // Check if device supports Google Play
    await GoogleSignin.hasPlayServices({ showPlayServicesUpdateDialog: true });

    // Get users ID token
    const { idToken } = await GoogleSignin.signIn();

    // Create a Google credential with the token
    const googleCredential = auth.GoogleAuthProvider.credential(idToken);

    // Sign-in the user with the credential
    const userCredential = await auth().signInWithCredential(googleCredential);

    return {
      user: mapFirebaseUser(userCredential.user),
    };
  } catch (error: any) {
    return {
      user: null,
      error: mapAuthError(error),
    };
  }
}

/**
 * Sign in with Apple (iOS only)
 */
export async function signInWithApple(): Promise<{
  user: FirebaseUser | null;
  error?: AuthError;
}> {
  try {
    // Start the sign-in request
    const appleAuthRequestResponse = await appleAuth.performRequest({
      requestedOperation: appleAuth.Operation.LOGIN,
      requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
    });

    // Ensure Apple returned a user identityToken
    if (!appleAuthRequestResponse.identityToken) {
      throw new Error('Apple Sign-In failed - no identity token returned');
    }

    // Create a Firebase credential from the response
    const { identityToken, nonce } = appleAuthRequestResponse;
    const appleCredential = auth.AppleAuthProvider.credential(identityToken, nonce);

    // Sign the user in with the credential
    const userCredential = await auth().signInWithCredential(appleCredential);

    return {
      user: mapFirebaseUser(userCredential.user),
    };
  } catch (error: any) {
    return {
      user: null,
      error: mapAuthError(error),
    };
  }
}

/**
 * Sign out
 */
export async function signOut(): Promise<{ error?: AuthError }> {
  try {
    await auth().signOut();

    // Also sign out from Google if signed in
    const isSignedIn = await GoogleSignin.isSignedIn();
    if (isSignedIn) {
      await GoogleSignin.revokeAccess();
      await GoogleSignin.signOut();
    }

    return {};
  } catch (error: any) {
    return {
      error: mapAuthError(error),
    };
  }
}

/**
 * Get current user
 */
export function getCurrentUser(): FirebaseUser | null {
  const user = auth().currentUser;
  return user ? mapFirebaseUser(user) : null;
}

/**
 * Send password reset email
 */
export async function sendPasswordResetEmail(email: string): Promise<{ error?: AuthError }> {
  try {
    await auth().sendPasswordResetEmail(email);
    return {};
  } catch (error: any) {
    return {
      error: mapAuthError(error),
    };
  }
}

/**
 * Update user profile
 */
export async function updateUserProfile(updates: {
  displayName?: string;
  photoURL?: string;
}): Promise<{ error?: AuthError }> {
  try {
    const user = auth().currentUser;
    if (!user) {
      throw new Error('No user signed in');
    }

    await user.updateProfile(updates);
    return {};
  } catch (error: any) {
    return {
      error: mapAuthError(error),
    };
  }
}

/**
 * Update email
 */
export async function updateEmail(newEmail: string): Promise<{ error?: AuthError }> {
  try {
    const user = auth().currentUser;
    if (!user) {
      throw new Error('No user signed in');
    }

    await user.updateEmail(newEmail);
    return {};
  } catch (error: any) {
    return {
      error: mapAuthError(error),
    };
  }
}

/**
 * Update password
 */
export async function updatePassword(newPassword: string): Promise<{ error?: AuthError }> {
  try {
    const user = auth().currentUser;
    if (!user) {
      throw new Error('No user signed in');
    }

    await user.updatePassword(newPassword);
    return {};
  } catch (error: any) {
    return {
      error: mapAuthError(error),
    };
  }
}

/**
 * Delete user account
 */
export async function deleteAccount(): Promise<{ error?: AuthError }> {
  try {
    const user = auth().currentUser;
    if (!user) {
      throw new Error('No user signed in');
    }

    await user.delete();
    return {};
  } catch (error: any) {
    return {
      error: mapAuthError(error),
    };
  }
}

/**
 * Subscribe to auth state changes
 */
export function onAuthStateChanged(
  callback: (user: FirebaseUser | null) => void
): () => void {
  return auth().onAuthStateChanged((user) => {
    callback(user ? mapFirebaseUser(user) : null);
  });
}

// Helper functions

/**
 * Map Firebase user to our user type
 */
function mapFirebaseUser(user: FirebaseAuthTypes.User): FirebaseUser {
  return {
    uid: user.uid,
    email: user.email,
    displayName: user.displayName,
    photoURL: user.photoURL,
    emailVerified: user.emailVerified,
    phoneNumber: user.phoneNumber,
    isAnonymous: user.isAnonymous,
    metadata: {
      creationTime: user.metadata.creationTime,
      lastSignInTime: user.metadata.lastSignInTime,
    },
    providerData: user.providerData.map((provider) => ({
      providerId: provider.providerId,
      uid: provider.uid,
      displayName: provider.displayName,
      email: provider.email,
      photoURL: provider.photoURL,
      phoneNumber: provider.phoneNumber,
    })),
  };
}

/**
 * Map Firebase error to our error type
 */
function mapAuthError(error: any): AuthError {
  const code = error.code || 'unknown';
  const message = error.message || 'An unknown error occurred';

  // Map common Firebase auth error codes to user-friendly messages
  const friendlyMessages: Record<string, string> = {
    'auth/email-already-in-use': 'This email is already registered',
    'auth/invalid-email': 'Invalid email address',
    'auth/user-not-found': 'No account found with this email',
    'auth/wrong-password': 'Incorrect password',
    'auth/weak-password': 'Password should be at least 6 characters',
    'auth/user-disabled': 'This account has been disabled',
    'auth/too-many-requests': 'Too many failed attempts. Please try again later',
    'auth/network-request-failed': 'Network error. Please check your connection',
    'auth/requires-recent-login': 'Please sign in again to complete this action',
  };

  return {
    code,
    message: friendlyMessages[code] || message,
    originalError: error,
  };
}
`;
}
