// Firebase TypeScript types template
// Auto-generated by Mobigen Firebase Connector

import type { CodeGenContext } from '@mobigen/connectors/core';

export function firebaseTypesTemplate(ctx: CodeGenContext): string {
  return `/**
 * Firebase TypeScript Types
 * Auto-generated for ${ctx.projectConfig.appName}
 *
 * Common TypeScript types for Firebase services.
 */

/**
 * Firebase User type
 */
export interface FirebaseUser {
  uid: string;
  email: string | null;
  displayName: string | null;
  photoURL: string | null;
  emailVerified: boolean;
  phoneNumber: string | null;
  isAnonymous: boolean;
  metadata: {
    creationTime?: string;
    lastSignInTime?: string;
  };
  providerData: Array<{
    providerId: string;
    uid: string;
    displayName: string | null;
    email: string | null;
    photoURL: string | null;
    phoneNumber: string | null;
  }>;
}

/**
 * Authentication error type
 */
export interface AuthError {
  code: string;
  message: string;
  originalError?: any;
}

/**
 * Firestore error type
 */
export interface FirestoreError {
  code: string;
  message: string;
  originalError?: any;
}

/**
 * Storage error type
 */
export interface StorageError {
  code: string;
  message: string;
  originalError?: any;
}

/**
 * Base Firestore document with timestamps
 */
export interface FirebaseDocument {
  id: string;
  createdAt?: any; // Firestore Timestamp
  updatedAt?: any; // Firestore Timestamp
}

/**
 * Firestore query options
 */
export interface QueryOptions {
  limit?: number;
  orderBy?: {
    field: string;
    direction?: 'asc' | 'desc';
  };
  startAfter?: any;
  endBefore?: any;
}

/**
 * Firestore where condition
 */
export interface WhereCondition {
  field: string;
  operator: '==' | '!=' | '<' | '<=' | '>' | '>=' | 'array-contains' | 'in' | 'not-in' | 'array-contains-any';
  value: any;
}

/**
 * Batch write operation
 */
export type BatchOperation<T = any> =
  | { type: 'set'; id: string; data: Partial<T> }
  | { type: 'update'; id: string; data: Partial<T> }
  | { type: 'delete'; id: string };

/**
 * Upload progress event
 */
export interface UploadProgress {
  bytesTransferred: number;
  totalBytes: number;
  progress: number; // 0-100
}

/**
 * Upload task state
 */
export type UploadTaskState = 'running' | 'paused' | 'success' | 'error' | 'canceled';

/**
 * Upload result
 */
export interface UploadResult {
  downloadURL: string;
  fullPath: string;
  metadata: {
    bucket: string;
    fullPath: string;
    generation: string;
    metageneration: string;
    name: string;
    size: number;
    timeCreated: string;
    updated: string;
    md5Hash?: string;
    cacheControl?: string;
    contentDisposition?: string;
    contentEncoding?: string;
    contentLanguage?: string;
    contentType?: string;
    customMetadata?: Record<string, string>;
  };
}

/**
 * Generic async result type
 */
export interface AsyncResult<T = any, E = any> {
  data?: T;
  error?: E;
  loading?: boolean;
}

/**
 * Hook result with data, loading, and error
 */
export interface UseFirebaseResult<T = any> {
  data: T | null;
  loading: boolean;
  error: FirestoreError | AuthError | StorageError | null;
}

/**
 * Mutation result
 */
export interface MutationResult<E = any> {
  success: boolean;
  error?: E;
  id?: string;
}

/**
 * Paginated data result
 */
export interface PaginatedResult<T = any> {
  data: T[];
  loading: boolean;
  error: FirestoreError | null;
  hasMore: boolean;
  loadMore: () => Promise<void>;
  reset: () => void;
}

// Common collection types for your app
// Customize these based on your data model

/**
 * Example: User profile document
 */
export interface UserProfile extends FirebaseDocument {
  uid: string;
  email: string;
  displayName: string;
  photoURL?: string;
  bio?: string;
  role: 'user' | 'admin';
  preferences?: Record<string, any>;
}

/**
 * Example: Post document
 */
export interface Post extends FirebaseDocument {
  title: string;
  content: string;
  authorId: string;
  authorName: string;
  authorPhotoURL?: string;
  imageURLs?: string[];
  likes: number;
  commentCount: number;
  isPublished: boolean;
  publishedAt?: any;
  tags?: string[];
}

/**
 * Example: Comment document
 */
export interface Comment extends FirebaseDocument {
  postId: string;
  authorId: string;
  authorName: string;
  authorPhotoURL?: string;
  content: string;
  likes: number;
  parentCommentId?: string;
}

/**
 * Example: Notification document
 */
export interface Notification extends FirebaseDocument {
  userId: string;
  type: 'like' | 'comment' | 'follow' | 'mention' | 'system';
  title: string;
  message: string;
  isRead: boolean;
  actionURL?: string;
  metadata?: Record<string, any>;
}
`;
}
