// Firebase Auth hooks template
// Auto-generated by Mobigen Firebase Connector

import type { CodeGenContext } from '@mobigen/connectors/core';

export function useFirebaseAuthTemplate(ctx: CodeGenContext): string {
  return `/**
 * Firebase Auth React Hooks
 * Auto-generated for ${ctx.projectConfig.appName}
 *
 * Provides React hooks for Firebase authentication.
 * Includes state management and automatic cleanup.
 */

import { useState, useEffect, useCallback } from 'react';
import type { FirebaseUser, AuthError } from '../types/firebase';
import {
  signInWithEmail as authSignInWithEmail,
  signUpWithEmail as authSignUpWithEmail,
  signInWithGoogle as authSignInWithGoogle,
  signInWithApple as authSignInWithApple,
  signOut as authSignOut,
  getCurrentUser,
  sendPasswordResetEmail as authSendPasswordResetEmail,
  updateUserProfile as authUpdateUserProfile,
  updateEmail as authUpdateEmail,
  updatePassword as authUpdatePassword,
  deleteAccount as authDeleteAccount,
  onAuthStateChanged,
} from '../services/firebase-auth';

/**
 * Hook for auth state
 * Automatically subscribes to auth state changes
 */
export function useAuth() {
  const [user, setUser] = useState<FirebaseUser | null>(getCurrentUser());
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<AuthError | null>(null);

  useEffect(() => {
    // Subscribe to auth state changes
    const unsubscribe = onAuthStateChanged((authUser) => {
      setUser(authUser);
      setLoading(false);
    });

    // Cleanup subscription
    return () => unsubscribe();
  }, []);

  return {
    user,
    loading,
    error,
    isAuthenticated: !!user,
  };
}

/**
 * Hook for email/password sign in
 */
export function useSignIn() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const signIn = useCallback(async (email: string, password: string) => {
    setLoading(true);
    setError(null);

    try {
      const result = await authSignInWithEmail(email, password);

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      return { success: true, user: result.user };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Sign in failed',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    signIn,
    loading,
    error,
  };
}

/**
 * Hook for email/password sign up
 */
export function useSignUp() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const signUp = useCallback(
    async (email: string, password: string, displayName?: string) => {
      setLoading(true);
      setError(null);

      try {
        const result = await authSignUpWithEmail(email, password, displayName);

        if (result.error) {
          setError(result.error);
          return { success: false, error: result.error };
        }

        return { success: true, user: result.user };
      } catch (err: any) {
        const authError: AuthError = {
          code: 'unknown',
          message: err.message || 'Sign up failed',
          originalError: err,
        };
        setError(authError);
        return { success: false, error: authError };
      } finally {
        setLoading(false);
      }
    },
    []
  );

  return {
    signUp,
    loading,
    error,
  };
}

/**
 * Hook for Google Sign-In
 */
export function useGoogleSignIn() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const signInWithGoogle = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await authSignInWithGoogle();

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      return { success: true, user: result.user };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Google sign in failed',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    signInWithGoogle,
    loading,
    error,
  };
}

/**
 * Hook for Apple Sign-In (iOS only)
 */
export function useAppleSignIn() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const signInWithApple = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await authSignInWithApple();

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      return { success: true, user: result.user };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Apple sign in failed',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    signInWithApple,
    loading,
    error,
  };
}

/**
 * Hook for sign out
 */
export function useSignOut() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const signOut = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await authSignOut();

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      return { success: true };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Sign out failed',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    signOut,
    loading,
    error,
  };
}

/**
 * Hook for password reset
 */
export function usePasswordReset() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);
  const [emailSent, setEmailSent] = useState(false);

  const sendPasswordResetEmail = useCallback(async (email: string) => {
    setLoading(true);
    setError(null);
    setEmailSent(false);

    try {
      const result = await authSendPasswordResetEmail(email);

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      setEmailSent(true);
      return { success: true };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Failed to send reset email',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    sendPasswordResetEmail,
    loading,
    error,
    emailSent,
  };
}

/**
 * Hook for updating user profile
 */
export function useUpdateProfile() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const updateProfile = useCallback(
    async (updates: { displayName?: string; photoURL?: string }) => {
      setLoading(true);
      setError(null);

      try {
        const result = await authUpdateUserProfile(updates);

        if (result.error) {
          setError(result.error);
          return { success: false, error: result.error };
        }

        return { success: true };
      } catch (err: any) {
        const authError: AuthError = {
          code: 'unknown',
          message: err.message || 'Failed to update profile',
          originalError: err,
        };
        setError(authError);
        return { success: false, error: authError };
      } finally {
        setLoading(false);
      }
    },
    []
  );

  return {
    updateProfile,
    loading,
    error,
  };
}

/**
 * Hook for updating email
 */
export function useUpdateEmail() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const updateEmail = useCallback(async (newEmail: string) => {
    setLoading(true);
    setError(null);

    try {
      const result = await authUpdateEmail(newEmail);

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      return { success: true };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Failed to update email',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    updateEmail,
    loading,
    error,
  };
}

/**
 * Hook for updating password
 */
export function useUpdatePassword() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const updatePassword = useCallback(async (newPassword: string) => {
    setLoading(true);
    setError(null);

    try {
      const result = await authUpdatePassword(newPassword);

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      return { success: true };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Failed to update password',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    updatePassword,
    loading,
    error,
  };
}

/**
 * Hook for deleting account
 */
export function useDeleteAccount() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AuthError | null>(null);

  const deleteAccount = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await authDeleteAccount();

      if (result.error) {
        setError(result.error);
        return { success: false, error: result.error };
      }

      return { success: true };
    } catch (err: any) {
      const authError: AuthError = {
        code: 'unknown',
        message: err.message || 'Failed to delete account',
        originalError: err,
      };
      setError(authError);
      return { success: false, error: authError };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    deleteAccount,
    loading,
    error,
  };
}
`;
}
