import type { Session, Track } from '@/types';

export const MOCK_TRACKS: Track[] = [
  {
    id: 'tech',
    name: 'Technology',
    description: 'Latest in tech and software development',
    color: '#3b82f6',
    icon: 'code',
  },
  {
    id: 'design',
    name: 'Design',
    description: 'UI/UX and product design',
    color: '#a855f7',
    icon: 'palette',
  },
  {
    id: 'business',
    name: 'Business',
    description: 'Strategy, growth, and leadership',
    color: '#22c55e',
    icon: 'briefcase',
  },
  {
    id: 'keynote',
    name: 'Keynote',
    description: 'Featured speakers and announcements',
    color: '#f59e0b',
    icon: 'mic',
  },
];

export const MOCK_SESSIONS: Session[] = [
  {
    id: '1',
    title: 'Opening Keynote: The Future of AI',
    description: 'Join us for an inspiring keynote about the transformative power of artificial intelligence and its impact on society.',
    startTime: '2026-03-15T09:00:00Z',
    endTime: '2026-03-15T10:00:00Z',
    trackId: 'keynote',
    trackName: 'Keynote',
    trackColor: '#f59e0b',
    speakerIds: ['1'],
    room: 'Main Hall',
    level: 'beginner',
    tags: ['AI', 'Future', 'Innovation'],
    capacity: 500,
    enrolled: 432,
  },
  {
    id: '2',
    title: 'Building Scalable React Native Apps',
    description: 'Learn best practices for architecting large-scale React Native applications with real-world examples.',
    startTime: '2026-03-15T10:30:00Z',
    endTime: '2026-03-15T11:30:00Z',
    trackId: 'tech',
    trackName: 'Technology',
    trackColor: '#3b82f6',
    speakerIds: ['2'],
    room: 'Room A',
    level: 'intermediate',
    tags: ['React Native', 'Mobile', 'Architecture'],
    capacity: 150,
    enrolled: 120,
  },
  {
    id: '3',
    title: 'Design Systems That Scale',
    description: 'Creating and maintaining design systems for large organizations and multi-platform products.',
    startTime: '2026-03-15T10:30:00Z',
    endTime: '2026-03-15T11:30:00Z',
    trackId: 'design',
    trackName: 'Design',
    trackColor: '#a855f7',
    speakerIds: ['3'],
    room: 'Room B',
    level: 'intermediate',
    tags: ['Design Systems', 'UI/UX', 'Collaboration'],
    capacity: 100,
    enrolled: 85,
  },
  {
    id: '4',
    title: 'Growth Hacking for Startups',
    description: 'Proven strategies to accelerate your startup growth without breaking the bank.',
    startTime: '2026-03-15T10:30:00Z',
    endTime: '2026-03-15T11:30:00Z',
    trackId: 'business',
    trackName: 'Business',
    trackColor: '#22c55e',
    speakerIds: ['4'],
    room: 'Room C',
    level: 'beginner',
    tags: ['Growth', 'Marketing', 'Startups'],
    capacity: 120,
    enrolled: 95,
  },
  {
    id: '5',
    title: 'Advanced TypeScript Patterns',
    description: 'Deep dive into advanced TypeScript patterns and techniques for type-safe applications.',
    startTime: '2026-03-15T12:00:00Z',
    endTime: '2026-03-15T13:00:00Z',
    trackId: 'tech',
    trackName: 'Technology',
    trackColor: '#3b82f6',
    speakerIds: ['5'],
    room: 'Room A',
    level: 'advanced',
    tags: ['TypeScript', 'JavaScript', 'Programming'],
    capacity: 150,
    enrolled: 140,
  },
  {
    id: '6',
    title: 'User Research That Drives Product Decisions',
    description: 'How to conduct effective user research and translate findings into actionable product improvements.',
    startTime: '2026-03-15T12:00:00Z',
    endTime: '2026-03-15T13:00:00Z',
    trackId: 'design',
    trackName: 'Design',
    trackColor: '#a855f7',
    speakerIds: ['6'],
    room: 'Room B',
    level: 'intermediate',
    tags: ['Research', 'Product', 'UX'],
    capacity: 100,
    enrolled: 78,
  },
  {
    id: '7',
    title: 'Building High-Performance Teams',
    description: 'Leadership strategies for creating and managing high-performing engineering teams.',
    startTime: '2026-03-15T12:00:00Z',
    endTime: '2026-03-15T13:00:00Z',
    trackId: 'business',
    trackName: 'Business',
    trackColor: '#22c55e',
    speakerIds: ['7'],
    room: 'Room C',
    level: 'intermediate',
    tags: ['Leadership', 'Teams', 'Management'],
    capacity: 120,
    enrolled: 110,
  },
  {
    id: '8',
    title: 'Cloud Architecture Best Practices',
    description: 'Building resilient and cost-effective cloud infrastructure on AWS, Azure, and GCP.',
    startTime: '2026-03-15T14:00:00Z',
    endTime: '2026-03-15T15:00:00Z',
    trackId: 'tech',
    trackName: 'Technology',
    trackColor: '#3b82f6',
    speakerIds: ['8'],
    room: 'Room A',
    level: 'advanced',
    tags: ['Cloud', 'Infrastructure', 'DevOps'],
    capacity: 150,
    enrolled: 125,
  },
  {
    id: '9',
    title: 'Designing for Accessibility',
    description: 'Creating inclusive digital experiences that work for everyone, including people with disabilities.',
    startTime: '2026-03-15T14:00:00Z',
    endTime: '2026-03-15T15:00:00Z',
    trackId: 'design',
    trackName: 'Design',
    trackColor: '#a855f7',
    speakerIds: ['9'],
    room: 'Room B',
    level: 'beginner',
    tags: ['Accessibility', 'Inclusive Design', 'UX'],
    capacity: 100,
    enrolled: 92,
  },
  {
    id: '10',
    title: 'Fundraising 101 for Tech Founders',
    description: 'Everything you need to know about raising venture capital for your tech startup.',
    startTime: '2026-03-15T14:00:00Z',
    endTime: '2026-03-15T15:00:00Z',
    trackId: 'business',
    trackName: 'Business',
    trackColor: '#22c55e',
    speakerIds: ['10'],
    room: 'Room C',
    level: 'beginner',
    tags: ['Fundraising', 'VC', 'Startups'],
    capacity: 120,
    enrolled: 118,
  },
  {
    id: '11',
    title: 'GraphQL vs REST: Making the Right Choice',
    description: 'Compare GraphQL and REST APIs to make informed architectural decisions for your project.',
    startTime: '2026-03-15T15:30:00Z',
    endTime: '2026-03-15T16:30:00Z',
    trackId: 'tech',
    trackName: 'Technology',
    trackColor: '#3b82f6',
    speakerIds: ['11'],
    room: 'Room A',
    level: 'intermediate',
    tags: ['GraphQL', 'REST', 'API'],
    capacity: 150,
    enrolled: 135,
  },
  {
    id: '12',
    title: 'Animation Principles for Web & Mobile',
    description: 'Learn fundamental animation principles and how to apply them in modern web and mobile apps.',
    startTime: '2026-03-15T15:30:00Z',
    endTime: '2026-03-15T16:30:00Z',
    trackId: 'design',
    trackName: 'Design',
    trackColor: '#a855f7',
    speakerIds: ['12'],
    room: 'Room B',
    level: 'intermediate',
    tags: ['Animation', 'Motion', 'UI'],
    capacity: 100,
    enrolled: 88,
  },
  {
    id: '13',
    title: 'Product-Market Fit: Finding Your North Star',
    description: 'Identifying and validating product-market fit before scaling your business.',
    startTime: '2026-03-15T15:30:00Z',
    endTime: '2026-03-15T16:30:00Z',
    trackId: 'business',
    trackName: 'Business',
    trackColor: '#22c55e',
    speakerIds: ['13'],
    room: 'Room C',
    level: 'intermediate',
    tags: ['Product', 'PMF', 'Strategy'],
    capacity: 120,
    enrolled: 105,
  },
  {
    id: '14',
    title: 'Security Best Practices for Modern Apps',
    description: 'Protecting your applications and users from common security vulnerabilities.',
    startTime: '2026-03-16T09:00:00Z',
    endTime: '2026-03-16T10:00:00Z',
    trackId: 'tech',
    trackName: 'Technology',
    trackColor: '#3b82f6',
    speakerIds: ['14'],
    room: 'Room A',
    level: 'intermediate',
    tags: ['Security', 'Authentication', 'Privacy'],
    capacity: 150,
    enrolled: 145,
  },
  {
    id: '15',
    title: 'Designing for Global Audiences',
    description: 'Creating products that resonate across different cultures and languages.',
    startTime: '2026-03-16T09:00:00Z',
    endTime: '2026-03-16T10:00:00Z',
    trackId: 'design',
    trackName: 'Design',
    trackColor: '#a855f7',
    speakerIds: ['15'],
    room: 'Room B',
    level: 'intermediate',
    tags: ['Localization', 'Global', 'Culture'],
    capacity: 100,
    enrolled: 72,
  },
  {
    id: '16',
    title: 'Building a Remote-First Company',
    description: 'Best practices for creating and managing successful distributed teams.',
    startTime: '2026-03-16T09:00:00Z',
    endTime: '2026-03-16T10:00:00Z',
    trackId: 'business',
    trackName: 'Business',
    trackColor: '#22c55e',
    speakerIds: ['4'],
    room: 'Room C',
    level: 'beginner',
    tags: ['Remote', 'Culture', 'Teams'],
    capacity: 120,
    enrolled: 98,
  },
  {
    id: '17',
    title: 'Machine Learning in Production',
    description: 'Deploying and maintaining ML models in production environments at scale.',
    startTime: '2026-03-16T10:30:00Z',
    endTime: '2026-03-16T11:30:00Z',
    trackId: 'tech',
    trackName: 'Technology',
    trackColor: '#3b82f6',
    speakerIds: ['1'],
    room: 'Room A',
    level: 'advanced',
    tags: ['ML', 'AI', 'Production'],
    capacity: 150,
    enrolled: 142,
  },
  {
    id: '18',
    title: 'Design Critique: Do it Right',
    description: 'How to give and receive effective design feedback that improves your work.',
    startTime: '2026-03-16T10:30:00Z',
    endTime: '2026-03-16T11:30:00Z',
    trackId: 'design',
    trackName: 'Design',
    trackColor: '#a855f7',
    speakerIds: ['3'],
    room: 'Room B',
    level: 'beginner',
    tags: ['Critique', 'Feedback', 'Collaboration'],
    capacity: 100,
    enrolled: 81,
  },
  {
    id: '19',
    title: 'Metrics That Matter for SaaS',
    description: 'Understanding and optimizing the key metrics that drive SaaS business growth.',
    startTime: '2026-03-16T10:30:00Z',
    endTime: '2026-03-16T11:30:00Z',
    trackId: 'business',
    trackName: 'Business',
    trackColor: '#22c55e',
    speakerIds: ['7'],
    room: 'Room C',
    level: 'intermediate',
    tags: ['Metrics', 'SaaS', 'Analytics'],
    capacity: 120,
    enrolled: 112,
  },
  {
    id: '20',
    title: 'Closing Keynote: Building for the Next Billion',
    description: 'Inspirational talk about creating technology that serves emerging markets and underserved communities.',
    startTime: '2026-03-16T16:00:00Z',
    endTime: '2026-03-16T17:00:00Z',
    trackId: 'keynote',
    trackName: 'Keynote',
    trackColor: '#f59e0b',
    speakerIds: ['15'],
    room: 'Main Hall',
    level: 'beginner',
    tags: ['Impact', 'Emerging Markets', 'Social Good'],
    capacity: 500,
    enrolled: 468,
  },
];

export async function fetchSessions(): Promise<Session[]> {
  await new Promise((resolve) => setTimeout(resolve, 500));
  return MOCK_SESSIONS;
}

export async function fetchSessionById(id: string): Promise<Session | null> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return MOCK_SESSIONS.find((s) => s.id === id) || null;
}

export async function fetchSessionsByTrack(trackId: string): Promise<Session[]> {
  await new Promise((resolve) => setTimeout(resolve, 400));
  return MOCK_SESSIONS.filter((s) => s.trackId === trackId);
}

export async function fetchTracks(): Promise<Track[]> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return MOCK_TRACKS;
}
