import type { Speaker } from '@/types';

export const MOCK_SPEAKERS: Speaker[] = [
  {
    id: '1',
    name: 'Dr. Sarah Chen',
    title: 'Chief AI Officer',
    company: 'TechVision AI',
    bio: 'Dr. Chen is a leading expert in artificial intelligence with over 15 years of experience. She has published 50+ research papers and holds 12 patents in machine learning.',
    avatar: 'https://i.pravatar.cc/400?img=1',
    twitter: '@sarahchen',
    linkedin: 'sarah-chen',
    website: 'https://sarahchen.ai',
    sessionIds: ['1', '17'],
  },
  {
    id: '2',
    name: 'Marcus Rodriguez',
    title: 'Senior Mobile Architect',
    company: 'Airbnb',
    bio: 'Marcus has been building mobile apps for over a decade and currently leads the mobile architecture team at Airbnb. He\'s passionate about developer experience and app performance.',
    avatar: 'https://i.pravatar.cc/400?img=12',
    twitter: '@marcusrod',
    linkedin: 'marcus-rodriguez',
    sessionIds: ['2'],
  },
  {
    id: '3',
    name: 'Emily Watson',
    title: 'Design Director',
    company: 'Figma',
    bio: 'Emily leads the design systems team at Figma. She has worked with companies like Apple and Google, helping them build world-class design systems.',
    avatar: 'https://i.pravatar.cc/400?img=5',
    twitter: '@emilywatson',
    linkedin: 'emily-watson-design',
    website: 'https://emilywatson.design',
    sessionIds: ['3', '18'],
  },
  {
    id: '4',
    name: 'James Kim',
    title: 'Founder & CEO',
    company: 'GrowthLab',
    bio: 'James has helped over 100 startups achieve product-market fit and scale. He\'s a Y Combinator alum and angel investor.',
    avatar: 'https://i.pravatar.cc/400?img=13',
    twitter: '@jameskim',
    linkedin: 'james-kim-growth',
    sessionIds: ['4', '16'],
  },
  {
    id: '5',
    name: 'Alexandra Ivanova',
    title: 'TypeScript Core Team',
    company: 'Microsoft',
    bio: 'Alexandra is a member of the TypeScript core team at Microsoft, working on type inference and language features.',
    avatar: 'https://i.pravatar.cc/400?img=9',
    twitter: '@alexivanova',
    linkedin: 'alexandra-ivanova',
    sessionIds: ['5'],
  },
  {
    id: '6',
    name: 'David Park',
    title: 'Head of User Research',
    company: 'Spotify',
    bio: 'David leads user research at Spotify, conducting studies that inform product decisions for millions of users worldwide.',
    avatar: 'https://i.pravatar.cc/400?img=14',
    linkedin: 'david-park-research',
    sessionIds: ['6'],
  },
  {
    id: '7',
    name: 'Rachel Thompson',
    title: 'VP of Engineering',
    company: 'Stripe',
    bio: 'Rachel has built and scaled engineering teams at Stripe, Dropbox, and Facebook. She\'s known for her people-first leadership approach.',
    avatar: 'https://i.pravatar.cc/400?img=10',
    twitter: '@rachelthompson',
    linkedin: 'rachel-thompson-eng',
    sessionIds: ['7', '19'],
  },
  {
    id: '8',
    name: 'Ahmed Hassan',
    title: 'Cloud Architect',
    company: 'AWS',
    bio: 'Ahmed is a principal cloud architect at AWS with expertise in serverless, containers, and multi-cloud deployments.',
    avatar: 'https://i.pravatar.cc/400?img=15',
    twitter: '@ahmedhassan',
    linkedin: 'ahmed-hassan-cloud',
    sessionIds: ['8'],
  },
  {
    id: '9',
    name: 'Lisa Martinez',
    title: 'Accessibility Lead',
    company: 'Adobe',
    bio: 'Lisa champions accessibility at Adobe, ensuring products are usable by everyone. She\'s an advocate for inclusive design practices.',
    avatar: 'https://i.pravatar.cc/400?img=20',
    twitter: '@lisamartinez',
    linkedin: 'lisa-martinez-a11y',
    website: 'https://a11y.design',
    sessionIds: ['9'],
  },
  {
    id: '10',
    name: 'Michael Chang',
    title: 'Partner',
    company: 'Sequoia Capital',
    bio: 'Michael is a partner at Sequoia Capital, where he focuses on early-stage investments in enterprise and developer tools.',
    avatar: 'https://i.pravatar.cc/400?img=33',
    twitter: '@michaelchang',
    linkedin: 'michael-chang-vc',
    sessionIds: ['10'],
  },
  {
    id: '11',
    name: 'Nina Patel',
    title: 'Staff Engineer',
    company: 'Netflix',
    bio: 'Nina architected Netflix\'s GraphQL API infrastructure, serving millions of requests per second.',
    avatar: 'https://i.pravatar.cc/400?img=44',
    twitter: '@ninapatel',
    linkedin: 'nina-patel-eng',
    sessionIds: ['11'],
  },
  {
    id: '12',
    name: 'Chris Anderson',
    title: 'Motion Designer',
    company: 'Apple',
    bio: 'Chris creates delightful animations for Apple\'s iOS and macOS platforms. He\'s taught motion design at RISD and Parsons.',
    avatar: 'https://i.pravatar.cc/400?img=52',
    twitter: '@chrisanderson',
    linkedin: 'chris-anderson-motion',
    website: 'https://chrisanderson.design',
    sessionIds: ['12'],
  },
  {
    id: '13',
    name: 'Samantha Lee',
    title: 'Product Lead',
    company: 'Notion',
    bio: 'Samantha led product at several successful startups before joining Notion. She\'s obsessed with finding product-market fit.',
    avatar: 'https://i.pravatar.cc/400?img=47',
    twitter: '@samlee',
    linkedin: 'samantha-lee-product',
    sessionIds: ['13'],
  },
  {
    id: '14',
    name: 'Kevin O\'Brien',
    title: 'Security Engineer',
    company: 'Google',
    bio: 'Kevin works on Google\'s security infrastructure, protecting billions of users. He previously worked at the NSA.',
    avatar: 'https://i.pravatar.cc/400?img=59',
    twitter: '@kevinobrien',
    linkedin: 'kevin-obrien-security',
    sessionIds: ['14'],
  },
  {
    id: '15',
    name: 'Priya Sharma',
    title: 'Global Impact Director',
    company: 'Meta',
    bio: 'Priya leads Meta\'s initiatives to bring internet access to underserved communities worldwide. She\'s a TED speaker and author.',
    avatar: 'https://i.pravatar.cc/400?img=48',
    twitter: '@priyasharma',
    linkedin: 'priya-sharma-impact',
    website: 'https://priyasharma.org',
    sessionIds: ['15', '20'],
  },
];

export async function fetchSpeakers(): Promise<Speaker[]> {
  await new Promise((resolve) => setTimeout(resolve, 500));
  return MOCK_SPEAKERS;
}

export async function fetchSpeakerById(id: string): Promise<Speaker | null> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return MOCK_SPEAKERS.find((s) => s.id === id) || null;
}
