import { Player, PlayerPosition } from '@/types';

export const MOCK_PLAYERS: Player[] = [
  {
    id: 'player-1',
    name: 'Marcus Rodriguez',
    number: 10,
    position: 'Forward' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400',
    age: 26,
    height: '6\'1"',
    weight: '175 lbs',
    nationality: 'USA',
    bio: 'Team captain and leading scorer. Known for his explosive speed and clinical finishing.',
    stats: {
      gamesPlayed: 28,
      gamesStarted: 28,
      minutes: 2420,
      goals: 18,
      assists: 7,
      yellowCards: 3,
      redCards: 0,
    },
    socialMedia: {
      twitter: '@mrodriguez10',
      instagram: '@marcusrod',
    },
  },
  {
    id: 'player-2',
    name: 'David Chen',
    number: 1,
    position: 'Goalkeeper' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    age: 29,
    height: '6\'3"',
    weight: '185 lbs',
    nationality: 'Canada',
    bio: 'Veteran goalkeeper with incredible reflexes and leadership.',
    stats: {
      gamesPlayed: 30,
      gamesStarted: 30,
      minutes: 2700,
      goals: 0,
      assists: 0,
      yellowCards: 1,
      redCards: 0,
    },
    socialMedia: {
      instagram: '@davidchen1',
    },
  },
  {
    id: 'player-3',
    name: 'James Wilson',
    number: 7,
    position: 'Midfielder' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400',
    age: 24,
    height: '5\'11"',
    weight: '170 lbs',
    nationality: 'England',
    bio: 'Creative playmaker with exceptional vision and passing ability.',
    stats: {
      gamesPlayed: 27,
      gamesStarted: 25,
      minutes: 2180,
      goals: 8,
      assists: 12,
      yellowCards: 5,
      redCards: 0,
    },
    socialMedia: {
      twitter: '@jwilson7',
      instagram: '@jameswilson',
    },
  },
  {
    id: 'player-4',
    name: 'Alex Thompson',
    number: 5,
    position: 'Defender' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400',
    age: 28,
    height: '6\'2"',
    weight: '180 lbs',
    nationality: 'USA',
    bio: 'Rock-solid defender and aerial threat from set pieces.',
    stats: {
      gamesPlayed: 29,
      gamesStarted: 29,
      minutes: 2610,
      goals: 3,
      assists: 2,
      yellowCards: 8,
      redCards: 1,
    },
  },
  {
    id: 'player-5',
    name: 'Carlos Santos',
    number: 11,
    position: 'Forward' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400',
    age: 22,
    height: '5\'10"',
    weight: '165 lbs',
    nationality: 'Brazil',
    bio: 'Young prospect with incredible dribbling skills and flair.',
    stats: {
      gamesPlayed: 25,
      gamesStarted: 18,
      minutes: 1650,
      goals: 9,
      assists: 6,
      yellowCards: 2,
      redCards: 0,
    },
    socialMedia: {
      instagram: '@carlossantos11',
    },
  },
  {
    id: 'player-6',
    name: 'Mohamed Hassan',
    number: 8,
    position: 'Midfielder' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400',
    age: 27,
    height: '5\'9"',
    weight: '160 lbs',
    nationality: 'Egypt',
    bio: 'Box-to-box midfielder with tireless work rate.',
    stats: {
      gamesPlayed: 28,
      gamesStarted: 26,
      minutes: 2340,
      goals: 5,
      assists: 8,
      yellowCards: 6,
      redCards: 0,
    },
  },
  {
    id: 'player-7',
    name: 'Luke Anderson',
    number: 3,
    position: 'Defender' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    age: 25,
    height: '6\'0"',
    weight: '175 lbs',
    nationality: 'Australia',
    bio: 'Fast and aggressive fullback who loves to attack.',
    stats: {
      gamesPlayed: 26,
      gamesStarted: 24,
      minutes: 2220,
      goals: 2,
      assists: 5,
      yellowCards: 4,
      redCards: 0,
    },
  },
  {
    id: 'player-8',
    name: 'Diego Martinez',
    number: 9,
    position: 'Forward' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400',
    age: 30,
    height: '6\'1"',
    weight: '180 lbs',
    nationality: 'Spain',
    bio: 'Experienced striker with a nose for goal.',
    stats: {
      gamesPlayed: 24,
      gamesStarted: 20,
      minutes: 1890,
      goals: 12,
      assists: 3,
      yellowCards: 2,
      redCards: 0,
    },
  },
  {
    id: 'player-9',
    name: 'Tyler Park',
    number: 6,
    position: 'Midfielder' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400',
    age: 23,
    height: '5\'11"',
    weight: '170 lbs',
    nationality: 'South Korea',
    bio: 'Defensive midfielder with excellent tactical awareness.',
    stats: {
      gamesPlayed: 27,
      gamesStarted: 22,
      minutes: 2010,
      goals: 2,
      assists: 4,
      yellowCards: 7,
      redCards: 0,
    },
  },
  {
    id: 'player-10',
    name: 'Rafael Silva',
    number: 4,
    position: 'Defender' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400',
    age: 31,
    height: '6\'2"',
    weight: '185 lbs',
    nationality: 'Portugal',
    bio: 'Experienced center-back and defensive leader.',
    stats: {
      gamesPlayed: 28,
      gamesStarted: 28,
      minutes: 2520,
      goals: 1,
      assists: 1,
      yellowCards: 5,
      redCards: 0,
    },
  },
  {
    id: 'player-11',
    name: 'Kevin OBrien',
    number: 14,
    position: 'Midfielder' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400',
    age: 21,
    height: '5\'10"',
    weight: '165 lbs',
    nationality: 'Ireland',
    bio: 'Young talent with great potential and energy.',
    stats: {
      gamesPlayed: 18,
      gamesStarted: 8,
      minutes: 980,
      goals: 3,
      assists: 2,
      yellowCards: 1,
      redCards: 0,
    },
  },
  {
    id: 'player-12',
    name: 'Andre Kofi',
    number: 2,
    position: 'Defender' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400',
    age: 26,
    height: '6\'1"',
    weight: '178 lbs',
    nationality: 'Ghana',
    bio: 'Strong and quick fullback with great crossing ability.',
    stats: {
      gamesPlayed: 25,
      gamesStarted: 23,
      minutes: 2130,
      goals: 1,
      assists: 6,
      yellowCards: 3,
      redCards: 0,
    },
  },
  {
    id: 'player-13',
    name: 'Sebastian Muller',
    number: 13,
    position: 'Goalkeeper' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400',
    age: 24,
    height: '6\'2"',
    weight: '180 lbs',
    nationality: 'Germany',
    bio: 'Backup goalkeeper with excellent shot-stopping ability.',
    stats: {
      gamesPlayed: 4,
      gamesStarted: 4,
      minutes: 360,
      goals: 0,
      assists: 0,
      yellowCards: 0,
      redCards: 0,
    },
  },
  {
    id: 'player-14',
    name: 'Liam Murphy',
    number: 17,
    position: 'Forward' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400',
    age: 20,
    height: '5\'11"',
    weight: '168 lbs',
    nationality: 'Scotland',
    bio: 'Promising young forward learning from the veterans.',
    stats: {
      gamesPlayed: 15,
      gamesStarted: 5,
      minutes: 620,
      goals: 2,
      assists: 1,
      yellowCards: 0,
      redCards: 0,
    },
  },
  {
    id: 'player-15',
    name: 'Hiroshi Tanaka',
    number: 18,
    position: 'Midfielder' as PlayerPosition,
    photo: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400',
    age: 25,
    height: '5\'8"',
    weight: '158 lbs',
    nationality: 'Japan',
    bio: 'Technical midfielder with precise passing.',
    stats: {
      gamesPlayed: 20,
      gamesStarted: 12,
      minutes: 1280,
      goals: 4,
      assists: 5,
      yellowCards: 2,
      redCards: 0,
    },
  },
];

export async function getPlayers(): Promise<Player[]> {
  await new Promise((resolve) => setTimeout(resolve, 500));
  return MOCK_PLAYERS.sort((a, b) => a.number - b.number);
}

export async function getPlayer(id: string): Promise<Player | undefined> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return MOCK_PLAYERS.find((player) => player.id === id);
}

export async function getPlayersByPosition(position: PlayerPosition): Promise<Player[]> {
  await new Promise((resolve) => setTimeout(resolve, 400));
  return MOCK_PLAYERS.filter((player) => player.position === position);
}

export async function getTopScorers(limit = 5): Promise<Player[]> {
  await new Promise((resolve) => setTimeout(resolve, 400));
  return MOCK_PLAYERS.filter((p) => p.stats.goals && p.stats.goals > 0)
    .sort((a, b) => (b.stats.goals || 0) - (a.stats.goals || 0))
    .slice(0, limit);
}
