// ============================================================================
// Mock Recipe Data Service
// ============================================================================

import { Recipe, Category } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Breakfast',
    description: 'Start your day right',
    icon: 'sunny',
    color: '#FFB84D',
    recipeCount: 3,
  },
  {
    id: '2',
    name: 'Lunch',
    description: 'Midday meals',
    icon: 'restaurant',
    color: '#66BB6A',
    recipeCount: 4,
  },
  {
    id: '3',
    name: 'Dinner',
    description: 'Evening delights',
    icon: 'moon',
    color: '#FF6B35',
    recipeCount: 5,
  },
  {
    id: '4',
    name: 'Dessert',
    description: 'Sweet treats',
    icon: 'ice-cream',
    color: '#EC4899',
    recipeCount: 3,
  },
  {
    id: '5',
    name: 'Appetizers',
    description: 'Start the meal',
    icon: 'fast-food',
    color: '#8B5CF6',
    recipeCount: 2,
  },
  {
    id: '6',
    name: 'Salads',
    description: 'Fresh and healthy',
    icon: 'leaf',
    color: '#10B981',
    recipeCount: 2,
  },
  {
    id: '7',
    name: 'Soups',
    description: 'Warm comfort',
    icon: 'nutrition',
    color: '#F59E0B',
    recipeCount: 1,
  },
];

export const MOCK_RECIPES: Recipe[] = [
  // BREAKFAST (3 recipes)
  {
    id: '1',
    name: 'Classic French Toast',
    description: 'Perfectly golden, crispy on the outside, soft and custardy inside. A breakfast favorite that never disappoints.',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800',
    categoryId: '1',
    prepTime: 10,
    cookTime: 10,
    totalTime: 20,
    servings: 4,
    difficulty: 'easy',
    featured: true,
    rating: 4.8,
    reviewCount: 324,
    author: 'Chef Marie',
    dateAdded: '2024-01-15',
    tags: ['breakfast', 'quick', 'vegetarian'],
    ingredients: [
      { id: '1-1', name: 'thick bread slices', amount: 8, unit: 'whole', notes: 'day-old brioche or challah works best' },
      { id: '1-2', name: 'large eggs', amount: 4, unit: 'whole' },
      { id: '1-3', name: 'whole milk', amount: 1, unit: 'cup' },
      { id: '1-4', name: 'vanilla extract', amount: 1, unit: 'tsp' },
      { id: '1-5', name: 'ground cinnamon', amount: 1, unit: 'tsp' },
      { id: '1-6', name: 'granulated sugar', amount: 2, unit: 'tbsp' },
      { id: '1-7', name: 'butter', amount: 2, unit: 'tbsp', notes: 'for cooking' },
      { id: '1-8', name: 'maple syrup', amount: 0, unit: 'whole', notes: 'for serving' },
      { id: '1-9', name: 'fresh berries', amount: 0, unit: 'whole', notes: 'optional topping' },
    ],
    steps: [
      { id: '1-s1', stepNumber: 1, instruction: 'In a shallow bowl, whisk together eggs, milk, vanilla, cinnamon, and sugar until well combined.' },
      { id: '1-s2', stepNumber: 2, instruction: 'Heat a large skillet or griddle over medium heat and add butter.' },
      { id: '1-s3', stepNumber: 3, instruction: 'Dip each bread slice into the egg mixture, ensuring both sides are well coated but not soggy.' },
      { id: '1-s4', stepNumber: 4, instruction: 'Cook bread slices for 3-4 minutes per side until golden brown and crispy.', duration: 4 },
      { id: '1-s5', stepNumber: 5, instruction: 'Serve immediately with maple syrup, butter, and fresh berries.' },
    ],
    nutrition: {
      calories: 310,
      protein: 12,
      carbs: 42,
      fat: 10,
      fiber: 2,
      sugar: 18,
    },
  },
  {
    id: '2',
    name: 'Avocado Toast with Poached Egg',
    description: 'Creamy avocado on crispy sourdough topped with a perfectly poached egg. Simple, healthy, and Instagram-worthy.',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
    categoryId: '1',
    prepTime: 5,
    cookTime: 10,
    totalTime: 15,
    servings: 2,
    difficulty: 'easy',
    rating: 4.6,
    reviewCount: 215,
    tags: ['breakfast', 'healthy', 'vegetarian'],
    ingredients: [
      { id: '2-1', name: 'sourdough bread', amount: 2, unit: 'whole', notes: 'thick slices' },
      { id: '2-2', name: 'ripe avocados', amount: 1, unit: 'whole' },
      { id: '2-3', name: 'fresh eggs', amount: 2, unit: 'whole' },
      { id: '2-4', name: 'lemon juice', amount: 1, unit: 'tsp' },
      { id: '2-5', name: 'red pepper flakes', amount: 0.25, unit: 'tsp' },
      { id: '2-6', name: 'salt', amount: 0, unit: 'pinch', notes: 'to taste' },
      { id: '2-7', name: 'black pepper', amount: 0, unit: 'pinch', notes: 'to taste' },
      { id: '2-8', name: 'cherry tomatoes', amount: 4, unit: 'whole', notes: 'halved, optional' },
    ],
    steps: [
      { id: '2-s1', stepNumber: 1, instruction: 'Toast sourdough bread until golden and crispy.' },
      { id: '2-s2', stepNumber: 2, instruction: 'Mash avocado with lemon juice, salt, and pepper in a bowl.' },
      { id: '2-s3', stepNumber: 3, instruction: 'Bring a pot of water to a gentle simmer. Add a splash of vinegar.' },
      { id: '2-s4', stepNumber: 4, instruction: 'Crack each egg into a small bowl, then gently slide into simmering water. Cook for 3-4 minutes.', duration: 4 },
      { id: '2-s5', stepNumber: 5, instruction: 'Spread mashed avocado on toast, top with poached egg, red pepper flakes, and cherry tomatoes.' },
    ],
    nutrition: {
      calories: 340,
      protein: 14,
      carbs: 28,
      fat: 20,
      fiber: 8,
      sugar: 2,
    },
  },
  {
    id: '3',
    name: 'Blueberry Pancakes',
    description: 'Fluffy buttermilk pancakes studded with juicy blueberries. Weekend breakfast perfection.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    categoryId: '1',
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 4,
    difficulty: 'easy',
    featured: true,
    rating: 4.9,
    reviewCount: 512,
    tags: ['breakfast', 'vegetarian', 'kid-friendly'],
    ingredients: [
      { id: '3-1', name: 'all-purpose flour', amount: 2, unit: 'cup' },
      { id: '3-2', name: 'baking powder', amount: 2, unit: 'tsp' },
      { id: '3-3', name: 'baking soda', amount: 0.5, unit: 'tsp' },
      { id: '3-4', name: 'salt', amount: 0.5, unit: 'tsp' },
      { id: '3-5', name: 'granulated sugar', amount: 2, unit: 'tbsp' },
      { id: '3-6', name: 'buttermilk', amount: 2, unit: 'cup' },
      { id: '3-7', name: 'large eggs', amount: 2, unit: 'whole' },
      { id: '3-8', name: 'melted butter', amount: 4, unit: 'tbsp' },
      { id: '3-9', name: 'fresh blueberries', amount: 1, unit: 'cup' },
    ],
    steps: [
      { id: '3-s1', stepNumber: 1, instruction: 'In a large bowl, whisk together flour, baking powder, baking soda, salt, and sugar.' },
      { id: '3-s2', stepNumber: 2, instruction: 'In another bowl, whisk buttermilk, eggs, and melted butter.' },
      { id: '3-s3', stepNumber: 3, instruction: 'Pour wet ingredients into dry ingredients and stir until just combined (some lumps are okay).' },
      { id: '3-s4', stepNumber: 4, instruction: 'Gently fold in blueberries. Do not overmix.' },
      { id: '3-s5', stepNumber: 5, instruction: 'Heat griddle to 375°F. Pour 1/4 cup batter per pancake. Cook until bubbles form, then flip and cook until golden.', duration: 3 },
    ],
    nutrition: {
      calories: 380,
      protein: 10,
      carbs: 54,
      fat: 14,
      fiber: 3,
      sugar: 12,
    },
  },

  // LUNCH (4 recipes)
  {
    id: '4',
    name: 'Caesar Salad with Grilled Chicken',
    description: 'Crisp romaine, creamy Caesar dressing, crunchy croutons, and tender grilled chicken. A satisfying lunch classic.',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
    categoryId: '2',
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    servings: 4,
    difficulty: 'medium',
    rating: 4.7,
    reviewCount: 289,
    tags: ['lunch', 'salad', 'high-protein'],
    ingredients: [
      { id: '4-1', name: 'romaine lettuce', amount: 2, unit: 'whole', notes: 'heads, chopped' },
      { id: '4-2', name: 'chicken breasts', amount: 2, unit: 'whole', notes: 'boneless, skinless' },
      { id: '4-3', name: 'parmesan cheese', amount: 0.5, unit: 'cup', notes: 'grated' },
      { id: '4-4', name: 'croutons', amount: 1, unit: 'cup' },
      { id: '4-5', name: 'Caesar dressing', amount: 0.75, unit: 'cup' },
      { id: '4-6', name: 'olive oil', amount: 2, unit: 'tbsp' },
      { id: '4-7', name: 'lemon', amount: 1, unit: 'whole', notes: 'for wedges' },
      { id: '4-8', name: 'black pepper', amount: 0, unit: 'pinch', notes: 'to taste' },
    ],
    steps: [
      { id: '4-s1', stepNumber: 1, instruction: 'Season chicken breasts with salt and pepper. Brush with olive oil.' },
      { id: '4-s2', stepNumber: 2, instruction: 'Grill chicken over medium-high heat for 6-7 minutes per side until cooked through.', duration: 14 },
      { id: '4-s3', stepNumber: 3, instruction: 'Let chicken rest for 5 minutes, then slice into strips.', duration: 5 },
      { id: '4-s4', stepNumber: 4, instruction: 'In a large bowl, toss romaine with Caesar dressing until evenly coated.' },
      { id: '4-s5', stepNumber: 5, instruction: 'Add croutons and half the parmesan. Toss again.' },
      { id: '4-s6', stepNumber: 6, instruction: 'Top with sliced chicken, remaining parmesan, and black pepper. Serve with lemon wedges.' },
    ],
    nutrition: {
      calories: 420,
      protein: 32,
      carbs: 18,
      fat: 26,
      fiber: 3,
      sugar: 2,
    },
  },
  {
    id: '5',
    name: 'Caprese Sandwich',
    description: 'Fresh mozzarella, ripe tomatoes, basil, and balsamic glaze on crusty ciabatta. Simple Italian perfection.',
    image: 'https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=800',
    categoryId: '2',
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    servings: 2,
    difficulty: 'easy',
    rating: 4.5,
    reviewCount: 178,
    tags: ['lunch', 'vegetarian', 'quick', 'italian'],
    ingredients: [
      { id: '5-1', name: 'ciabatta bread', amount: 1, unit: 'whole', notes: 'cut in half' },
      { id: '5-2', name: 'fresh mozzarella', amount: 8, unit: 'oz', notes: 'sliced' },
      { id: '5-3', name: 'ripe tomatoes', amount: 2, unit: 'whole', notes: 'large, sliced' },
      { id: '5-4', name: 'fresh basil leaves', amount: 12, unit: 'whole' },
      { id: '5-5', name: 'balsamic glaze', amount: 2, unit: 'tbsp' },
      { id: '5-6', name: 'extra virgin olive oil', amount: 2, unit: 'tbsp' },
      { id: '5-7', name: 'salt', amount: 0, unit: 'pinch', notes: 'to taste' },
      { id: '5-8', name: 'black pepper', amount: 0, unit: 'pinch', notes: 'to taste' },
    ],
    steps: [
      { id: '5-s1', stepNumber: 1, instruction: 'Slice ciabatta in half horizontally. Lightly toast if desired.' },
      { id: '5-s2', stepNumber: 2, instruction: 'Drizzle both cut sides with olive oil.' },
      { id: '5-s3', stepNumber: 3, instruction: 'Layer mozzarella slices on bottom half of bread.' },
      { id: '5-s4', stepNumber: 4, instruction: 'Add tomato slices, season with salt and pepper.' },
      { id: '5-s5', stepNumber: 5, instruction: 'Add fresh basil leaves and drizzle with balsamic glaze.' },
      { id: '5-s6', stepNumber: 6, instruction: 'Top with other half of bread. Cut into portions and serve.' },
    ],
    nutrition: {
      calories: 480,
      protein: 22,
      carbs: 48,
      fat: 22,
      fiber: 3,
      sugar: 6,
    },
  },
  {
    id: '6',
    name: 'Thai Chicken Lettuce Wraps',
    description: 'Ground chicken with Thai flavors, crunchy vegetables, wrapped in crisp lettuce. Light but satisfying.',
    image: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800',
    categoryId: '2',
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    servings: 4,
    difficulty: 'easy',
    rating: 4.8,
    reviewCount: 342,
    tags: ['lunch', 'asian', 'healthy', 'gluten-free'],
    ingredients: [
      { id: '6-1', name: 'ground chicken', amount: 1, unit: 'lb' },
      { id: '6-2', name: 'butter lettuce', amount: 1, unit: 'whole', notes: 'head, leaves separated' },
      { id: '6-3', name: 'red bell pepper', amount: 1, unit: 'whole', notes: 'diced' },
      { id: '6-4', name: 'water chestnuts', amount: 0.5, unit: 'cup', notes: 'diced' },
      { id: '6-5', name: 'green onions', amount: 3, unit: 'whole', notes: 'sliced' },
      { id: '6-6', name: 'garlic', amount: 3, unit: 'whole', notes: 'cloves, minced' },
      { id: '6-7', name: 'fresh ginger', amount: 1, unit: 'tbsp', notes: 'minced' },
      { id: '6-8', name: 'soy sauce', amount: 3, unit: 'tbsp' },
      { id: '6-9', name: 'rice vinegar', amount: 1, unit: 'tbsp' },
      { id: '6-10', name: 'sesame oil', amount: 1, unit: 'tsp' },
      { id: '6-11', name: 'sriracha', amount: 1, unit: 'tsp', notes: 'optional' },
    ],
    steps: [
      { id: '6-s1', stepNumber: 1, instruction: 'Heat a large skillet over medium-high heat. Add ground chicken and cook until browned, breaking up with a spoon.', duration: 6 },
      { id: '6-s2', stepNumber: 2, instruction: 'Add garlic and ginger, cook for 1 minute until fragrant.', duration: 1 },
      { id: '6-s3', stepNumber: 3, instruction: 'Add bell pepper and water chestnuts, cook for 2 minutes.', duration: 2 },
      { id: '6-s4', stepNumber: 4, instruction: 'Stir in soy sauce, rice vinegar, sesame oil, and sriracha. Cook for 1 minute.' },
      { id: '6-s5', stepNumber: 5, instruction: 'Remove from heat and stir in green onions.' },
      { id: '6-s6', stepNumber: 6, instruction: 'Spoon mixture into lettuce leaves and serve immediately.' },
    ],
    nutrition: {
      calories: 220,
      protein: 24,
      carbs: 12,
      fat: 8,
      fiber: 2,
      sugar: 4,
    },
  },
  {
    id: '7',
    name: 'Quinoa Buddha Bowl',
    description: 'Colorful bowl with quinoa, roasted vegetables, chickpeas, and tahini dressing. Healthy and delicious.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    categoryId: '2',
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    servings: 2,
    difficulty: 'easy',
    featured: true,
    rating: 4.7,
    reviewCount: 267,
    tags: ['lunch', 'vegan', 'healthy', 'gluten-free'],
    ingredients: [
      { id: '7-1', name: 'quinoa', amount: 1, unit: 'cup', notes: 'uncooked' },
      { id: '7-2', name: 'chickpeas', amount: 1, unit: 'cup', notes: 'cooked or canned' },
      { id: '7-3', name: 'sweet potato', amount: 1, unit: 'whole', notes: 'cubed' },
      { id: '7-4', name: 'broccoli florets', amount: 2, unit: 'cup' },
      { id: '7-5', name: 'avocado', amount: 1, unit: 'whole', notes: 'sliced' },
      { id: '7-6', name: 'tahini', amount: 3, unit: 'tbsp' },
      { id: '7-7', name: 'lemon juice', amount: 2, unit: 'tbsp' },
      { id: '7-8', name: 'olive oil', amount: 2, unit: 'tbsp' },
      { id: '7-9', name: 'garlic powder', amount: 0.5, unit: 'tsp' },
      { id: '7-10', name: 'salt and pepper', amount: 0, unit: 'pinch', notes: 'to taste' },
    ],
    steps: [
      { id: '7-s1', stepNumber: 1, instruction: 'Cook quinoa according to package directions. Set aside.' },
      { id: '7-s2', stepNumber: 2, instruction: 'Preheat oven to 400°F. Toss sweet potato and broccoli with olive oil, salt, and pepper.' },
      { id: '7-s3', stepNumber: 3, instruction: 'Roast vegetables for 20-25 minutes until tender and lightly browned.', duration: 25 },
      { id: '7-s4', stepNumber: 4, instruction: 'Make dressing by whisking tahini, lemon juice, garlic powder, and water until smooth.' },
      { id: '7-s5', stepNumber: 5, instruction: 'Divide quinoa between bowls. Top with roasted vegetables, chickpeas, and avocado.' },
      { id: '7-s6', stepNumber: 6, instruction: 'Drizzle with tahini dressing and serve warm.' },
    ],
    nutrition: {
      calories: 520,
      protein: 18,
      carbs: 68,
      fat: 22,
      fiber: 15,
      sugar: 8,
    },
  },

  // DINNER (5 recipes)
  {
    id: '8',
    name: 'Spaghetti Carbonara',
    description: 'Creamy Roman pasta with eggs, pecorino, and crispy pancetta. Comfort food at its finest.',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    categoryId: '3',
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 4,
    difficulty: 'medium',
    featured: true,
    rating: 4.9,
    reviewCount: 645,
    tags: ['dinner', 'italian', 'pasta'],
    ingredients: [
      { id: '8-1', name: 'spaghetti', amount: 1, unit: 'lb' },
      { id: '8-2', name: 'pancetta', amount: 6, unit: 'oz', notes: 'diced' },
      { id: '8-3', name: 'large eggs', amount: 4, unit: 'whole' },
      { id: '8-4', name: 'pecorino romano', amount: 1, unit: 'cup', notes: 'grated' },
      { id: '8-5', name: 'black pepper', amount: 1, unit: 'tsp', notes: 'freshly ground' },
      { id: '8-6', name: 'salt', amount: 0, unit: 'pinch', notes: 'for pasta water' },
    ],
    steps: [
      { id: '8-s1', stepNumber: 1, instruction: 'Bring a large pot of salted water to boil. Cook spaghetti until al dente.', duration: 10 },
      { id: '8-s2', stepNumber: 2, instruction: 'While pasta cooks, fry pancetta in a large skillet until crispy. Remove from heat.' },
      { id: '8-s3', stepNumber: 3, instruction: 'In a bowl, whisk eggs, pecorino, and black pepper.' },
      { id: '8-s4', stepNumber: 4, instruction: 'Reserve 1 cup pasta water, then drain pasta.' },
      { id: '8-s5', stepNumber: 5, instruction: 'Add hot pasta to skillet with pancetta. Toss to combine.' },
      { id: '8-s6', stepNumber: 6, instruction: 'Off heat, add egg mixture and toss quickly, adding pasta water to create creamy sauce. Serve immediately.' },
    ],
    nutrition: {
      calories: 580,
      protein: 28,
      carbs: 56,
      fat: 24,
      fiber: 2,
      sugar: 2,
    },
  },
  {
    id: '9',
    name: 'Honey Garlic Salmon',
    description: 'Pan-seared salmon with a sweet and savory glaze. Quick, healthy, and restaurant-quality.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    categoryId: '3',
    prepTime: 5,
    cookTime: 12,
    totalTime: 17,
    servings: 4,
    difficulty: 'easy',
    rating: 4.8,
    reviewCount: 428,
    tags: ['dinner', 'seafood', 'healthy', 'quick'],
    ingredients: [
      { id: '9-1', name: 'salmon fillets', amount: 4, unit: 'whole', notes: '6 oz each' },
      { id: '9-2', name: 'honey', amount: 3, unit: 'tbsp' },
      { id: '9-3', name: 'soy sauce', amount: 3, unit: 'tbsp' },
      { id: '9-4', name: 'garlic', amount: 4, unit: 'whole', notes: 'cloves, minced' },
      { id: '9-5', name: 'fresh ginger', amount: 1, unit: 'tsp', notes: 'minced' },
      { id: '9-6', name: 'olive oil', amount: 2, unit: 'tbsp' },
      { id: '9-7', name: 'lemon', amount: 1, unit: 'whole', notes: 'juiced' },
      { id: '9-8', name: 'sesame seeds', amount: 1, unit: 'tsp', notes: 'for garnish' },
      { id: '9-9', name: 'green onions', amount: 2, unit: 'whole', notes: 'sliced, for garnish' },
    ],
    steps: [
      { id: '9-s1', stepNumber: 1, instruction: 'Mix honey, soy sauce, garlic, ginger, and lemon juice in a bowl.' },
      { id: '9-s2', stepNumber: 2, instruction: 'Heat olive oil in a large skillet over medium-high heat.' },
      { id: '9-s3', stepNumber: 3, instruction: 'Season salmon with salt and pepper. Place skin-side up in skillet.' },
      { id: '9-s4', stepNumber: 4, instruction: 'Cook for 4 minutes, then flip and cook for 3 more minutes.', duration: 7 },
      { id: '9-s5', stepNumber: 5, instruction: 'Pour honey garlic sauce over salmon. Cook for 2 minutes, basting frequently.', duration: 2 },
      { id: '9-s6', stepNumber: 6, instruction: 'Garnish with sesame seeds and green onions. Serve with rice and vegetables.' },
    ],
    nutrition: {
      calories: 380,
      protein: 36,
      carbs: 14,
      fat: 20,
      fiber: 0,
      sugar: 12,
    },
  },
  {
    id: '10',
    name: 'Chicken Tikka Masala',
    description: 'Tender chicken in a creamy tomato curry sauce. Better than takeout, made at home.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    categoryId: '3',
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    servings: 6,
    difficulty: 'medium',
    featured: true,
    rating: 4.9,
    reviewCount: 892,
    tags: ['dinner', 'indian', 'curry', 'comfort-food'],
    ingredients: [
      { id: '10-1', name: 'chicken breasts', amount: 2, unit: 'lb', notes: 'cubed' },
      { id: '10-2', name: 'plain yogurt', amount: 1, unit: 'cup' },
      { id: '10-3', name: 'garam masala', amount: 2, unit: 'tsp' },
      { id: '10-4', name: 'ground cumin', amount: 1, unit: 'tsp' },
      { id: '10-5', name: 'paprika', amount: 1, unit: 'tsp' },
      { id: '10-6', name: 'onion', amount: 1, unit: 'whole', notes: 'large, diced' },
      { id: '10-7', name: 'garlic', amount: 6, unit: 'whole', notes: 'cloves, minced' },
      { id: '10-8', name: 'fresh ginger', amount: 2, unit: 'tbsp', notes: 'minced' },
      { id: '10-9', name: 'tomato sauce', amount: 2, unit: 'cup' },
      { id: '10-10', name: 'heavy cream', amount: 1, unit: 'cup' },
      { id: '10-11', name: 'butter', amount: 4, unit: 'tbsp' },
      { id: '10-12', name: 'cilantro', amount: 0.25, unit: 'cup', notes: 'fresh, chopped' },
    ],
    steps: [
      { id: '10-s1', stepNumber: 1, instruction: 'Marinate chicken in yogurt, garam masala, cumin, and paprika for at least 20 minutes.', duration: 20 },
      { id: '10-s2', stepNumber: 2, instruction: 'Heat 2 tbsp butter in large pan. Cook chicken until browned. Remove and set aside.' },
      { id: '10-s3', stepNumber: 3, instruction: 'In same pan, melt remaining butter. Sauté onion, garlic, and ginger until softened.' },
      { id: '10-s4', stepNumber: 4, instruction: 'Add tomato sauce and remaining spices. Simmer for 10 minutes.', duration: 10 },
      { id: '10-s5', stepNumber: 5, instruction: 'Stir in heavy cream and return chicken to pan. Simmer for 10 more minutes.', duration: 10 },
      { id: '10-s6', stepNumber: 6, instruction: 'Garnish with cilantro. Serve with basmati rice and naan bread.' },
    ],
    nutrition: {
      calories: 420,
      protein: 32,
      carbs: 12,
      fat: 28,
      fiber: 2,
      sugar: 6,
    },
  },
  {
    id: '11',
    name: 'Beef Tacos',
    description: 'Seasoned ground beef in crispy shells with all the fixings. Family taco night perfection.',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800',
    categoryId: '3',
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 4,
    difficulty: 'easy',
    rating: 4.7,
    reviewCount: 534,
    tags: ['dinner', 'mexican', 'quick', 'kid-friendly'],
    ingredients: [
      { id: '11-1', name: 'ground beef', amount: 1, unit: 'lb' },
      { id: '11-2', name: 'taco seasoning', amount: 2, unit: 'tbsp' },
      { id: '11-3', name: 'taco shells', amount: 12, unit: 'whole' },
      { id: '11-4', name: 'romaine lettuce', amount: 2, unit: 'cup', notes: 'shredded' },
      { id: '11-5', name: 'cheddar cheese', amount: 1, unit: 'cup', notes: 'shredded' },
      { id: '11-6', name: 'tomatoes', amount: 2, unit: 'whole', notes: 'diced' },
      { id: '11-7', name: 'sour cream', amount: 0.5, unit: 'cup' },
      { id: '11-8', name: 'salsa', amount: 1, unit: 'cup' },
      { id: '11-9', name: 'cilantro', amount: 0.25, unit: 'cup', notes: 'chopped, optional' },
    ],
    steps: [
      { id: '11-s1', stepNumber: 1, instruction: 'Brown ground beef in a large skillet over medium-high heat, breaking it up as it cooks.', duration: 8 },
      { id: '11-s2', stepNumber: 2, instruction: 'Drain excess fat. Add taco seasoning and 1/2 cup water. Simmer for 5 minutes.', duration: 5 },
      { id: '11-s3', stepNumber: 3, instruction: 'Warm taco shells according to package directions.' },
      { id: '11-s4', stepNumber: 4, instruction: 'Fill each shell with seasoned beef.' },
      { id: '11-s5', stepNumber: 5, instruction: 'Top with lettuce, cheese, tomatoes, sour cream, and salsa.' },
      { id: '11-s6', stepNumber: 6, instruction: 'Garnish with cilantro if desired. Serve immediately.' },
    ],
    nutrition: {
      calories: 450,
      protein: 26,
      carbs: 32,
      fat: 24,
      fiber: 4,
      sugar: 4,
    },
  },
  {
    id: '12',
    name: 'Vegetable Stir-Fry',
    description: 'Colorful veggies in a savory sauce over rice. Quick, healthy, and customizable.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
    categoryId: '3',
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    servings: 4,
    difficulty: 'easy',
    rating: 4.6,
    reviewCount: 312,
    tags: ['dinner', 'vegan', 'asian', 'healthy'],
    ingredients: [
      { id: '12-1', name: 'mixed vegetables', amount: 6, unit: 'cup', notes: 'broccoli, bell peppers, carrots, snap peas' },
      { id: '12-2', name: 'tofu', amount: 14, unit: 'oz', notes: 'firm, cubed (optional)' },
      { id: '12-3', name: 'soy sauce', amount: 4, unit: 'tbsp' },
      { id: '12-4', name: 'rice vinegar', amount: 2, unit: 'tbsp' },
      { id: '12-5', name: 'sesame oil', amount: 1, unit: 'tbsp' },
      { id: '12-6', name: 'garlic', amount: 4, unit: 'whole', notes: 'cloves, minced' },
      { id: '12-7', name: 'fresh ginger', amount: 1, unit: 'tbsp', notes: 'minced' },
      { id: '12-8', name: 'cornstarch', amount: 1, unit: 'tbsp' },
      { id: '12-9', name: 'vegetable oil', amount: 2, unit: 'tbsp' },
      { id: '12-10', name: 'green onions', amount: 3, unit: 'whole', notes: 'sliced' },
    ],
    steps: [
      { id: '12-s1', stepNumber: 1, instruction: 'Mix soy sauce, rice vinegar, sesame oil, and cornstarch in a small bowl. Set aside.' },
      { id: '12-s2', stepNumber: 2, instruction: 'Heat vegetable oil in a large wok or skillet over high heat.' },
      { id: '12-s3', stepNumber: 3, instruction: 'Add garlic and ginger, stir-fry for 30 seconds until fragrant.' },
      { id: '12-s4', stepNumber: 4, instruction: 'Add vegetables and tofu (if using). Stir-fry for 5-6 minutes until tender-crisp.', duration: 6 },
      { id: '12-s5', stepNumber: 5, instruction: 'Pour sauce over vegetables. Toss to coat. Cook for 2 minutes until sauce thickens.', duration: 2 },
      { id: '12-s6', stepNumber: 6, instruction: 'Garnish with green onions. Serve over rice or noodles.' },
    ],
    nutrition: {
      calories: 220,
      protein: 12,
      carbs: 18,
      fat: 12,
      fiber: 5,
      sugar: 6,
    },
  },

  // DESSERTS (3 recipes)
  {
    id: '13',
    name: 'Chocolate Chip Cookies',
    description: 'Classic homemade cookies with gooey chocolate chips. Crispy edges, soft centers.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800',
    categoryId: '4',
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    servings: 24,
    difficulty: 'easy',
    featured: true,
    rating: 5.0,
    reviewCount: 1243,
    tags: ['dessert', 'cookies', 'baking', 'kid-friendly'],
    ingredients: [
      { id: '13-1', name: 'all-purpose flour', amount: 2.25, unit: 'cup' },
      { id: '13-2', name: 'baking soda', amount: 1, unit: 'tsp' },
      { id: '13-3', name: 'salt', amount: 1, unit: 'tsp' },
      { id: '13-4', name: 'butter', amount: 1, unit: 'cup', notes: 'softened' },
      { id: '13-5', name: 'granulated sugar', amount: 0.75, unit: 'cup' },
      { id: '13-6', name: 'brown sugar', amount: 0.75, unit: 'cup', notes: 'packed' },
      { id: '13-7', name: 'vanilla extract', amount: 1, unit: 'tsp' },
      { id: '13-8', name: 'large eggs', amount: 2, unit: 'whole' },
      { id: '13-9', name: 'chocolate chips', amount: 2, unit: 'cup' },
    ],
    steps: [
      { id: '13-s1', stepNumber: 1, instruction: 'Preheat oven to 375°F. Line baking sheets with parchment paper.' },
      { id: '13-s2', stepNumber: 2, instruction: 'Mix flour, baking soda, and salt in a bowl. Set aside.' },
      { id: '13-s3', stepNumber: 3, instruction: 'Beat butter and both sugars until creamy. Add vanilla and eggs, beat well.' },
      { id: '13-s4', stepNumber: 4, instruction: 'Gradually add flour mixture. Stir in chocolate chips.' },
      { id: '13-s5', stepNumber: 5, instruction: 'Drop rounded tablespoons of dough onto baking sheets, 2 inches apart.' },
      { id: '13-s6', stepNumber: 6, instruction: 'Bake for 9-11 minutes until golden brown. Cool on baking sheet for 2 minutes, then transfer to wire rack.', duration: 11 },
    ],
    nutrition: {
      calories: 180,
      protein: 2,
      carbs: 24,
      fat: 9,
      fiber: 1,
      sugar: 16,
    },
  },
  {
    id: '14',
    name: 'New York Cheesecake',
    description: 'Rich, creamy, classic cheesecake with graham cracker crust. The ultimate dessert.',
    image: 'https://images.unsplash.com/photo-1533134242820-b4f818be9c8c?w=800',
    categoryId: '4',
    prepTime: 30,
    cookTime: 60,
    totalTime: 90,
    servings: 12,
    difficulty: 'hard',
    rating: 4.9,
    reviewCount: 678,
    tags: ['dessert', 'cheesecake', 'baking'],
    ingredients: [
      { id: '14-1', name: 'graham cracker crumbs', amount: 2, unit: 'cup' },
      { id: '14-2', name: 'butter', amount: 0.5, unit: 'cup', notes: 'melted' },
      { id: '14-3', name: 'cream cheese', amount: 32, unit: 'oz', notes: '4 packages, softened' },
      { id: '14-4', name: 'granulated sugar', amount: 1.25, unit: 'cup' },
      { id: '14-5', name: 'sour cream', amount: 1, unit: 'cup' },
      { id: '14-6', name: 'vanilla extract', amount: 2, unit: 'tsp' },
      { id: '14-7', name: 'large eggs', amount: 4, unit: 'whole' },
      { id: '14-8', name: 'all-purpose flour', amount: 3, unit: 'tbsp' },
    ],
    steps: [
      { id: '14-s1', stepNumber: 1, instruction: 'Preheat oven to 325°F. Mix graham cracker crumbs and melted butter. Press into 9-inch springform pan.' },
      { id: '14-s2', stepNumber: 2, instruction: 'Beat cream cheese until fluffy. Add sugar and beat until smooth.' },
      { id: '14-s3', stepNumber: 3, instruction: 'Add sour cream and vanilla. Mix well.' },
      { id: '14-s4', stepNumber: 4, instruction: 'Add eggs one at a time, beating just until combined. Stir in flour.' },
      { id: '14-s5', stepNumber: 5, instruction: 'Pour filling over crust. Bake for 55-60 minutes until edges are set but center jiggles slightly.', duration: 60 },
      { id: '14-s6', stepNumber: 6, instruction: 'Turn off oven, crack door open, and let cheesecake cool in oven for 1 hour. Refrigerate for at least 4 hours before serving.', duration: 240 },
    ],
    nutrition: {
      calories: 480,
      protein: 8,
      carbs: 38,
      fat: 33,
      fiber: 0,
      sugar: 28,
    },
  },
  {
    id: '15',
    name: 'Apple Pie',
    description: 'Classic American apple pie with flaky crust and cinnamon-spiced filling. Serve warm with ice cream.',
    image: 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800',
    categoryId: '4',
    prepTime: 30,
    cookTime: 50,
    totalTime: 80,
    servings: 8,
    difficulty: 'medium',
    rating: 4.8,
    reviewCount: 445,
    tags: ['dessert', 'pie', 'baking', 'american'],
    ingredients: [
      { id: '15-1', name: 'pie crusts', amount: 2, unit: 'whole', notes: 'homemade or store-bought' },
      { id: '15-2', name: 'granny smith apples', amount: 7, unit: 'whole', notes: 'peeled and sliced' },
      { id: '15-3', name: 'granulated sugar', amount: 0.75, unit: 'cup' },
      { id: '15-4', name: 'all-purpose flour', amount: 2, unit: 'tbsp' },
      { id: '15-5', name: 'ground cinnamon', amount: 1, unit: 'tsp' },
      { id: '15-6', name: 'ground nutmeg', amount: 0.25, unit: 'tsp' },
      { id: '15-7', name: 'lemon juice', amount: 1, unit: 'tbsp' },
      { id: '15-8', name: 'butter', amount: 2, unit: 'tbsp', notes: 'cut into small pieces' },
    ],
    steps: [
      { id: '15-s1', stepNumber: 1, instruction: 'Preheat oven to 425°F. Place one pie crust in 9-inch pie pan.' },
      { id: '15-s2', stepNumber: 2, instruction: 'In large bowl, toss apple slices with sugar, flour, cinnamon, nutmeg, and lemon juice.' },
      { id: '15-s3', stepNumber: 3, instruction: 'Pour apple mixture into pie crust. Dot with butter pieces.' },
      { id: '15-s4', stepNumber: 4, instruction: 'Cover with top crust. Seal and crimp edges. Cut slits in top for steam to escape.' },
      { id: '15-s5', stepNumber: 5, instruction: 'Bake for 45-50 minutes until crust is golden and filling is bubbly. Cover edges with foil if browning too quickly.', duration: 50 },
      { id: '15-s6', stepNumber: 6, instruction: 'Cool for at least 2 hours before slicing. Serve warm or at room temperature.' },
    ],
    nutrition: {
      calories: 380,
      protein: 3,
      carbs: 56,
      fat: 16,
      fiber: 4,
      sugar: 32,
    },
  },

  // APPETIZERS (2 recipes)
  {
    id: '16',
    name: 'Bruschetta',
    description: 'Toasted bread with fresh tomato, basil, and garlic topping. Classic Italian appetizer.',
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800',
    categoryId: '5',
    prepTime: 15,
    cookTime: 5,
    totalTime: 20,
    servings: 8,
    difficulty: 'easy',
    rating: 4.7,
    reviewCount: 234,
    tags: ['appetizer', 'italian', 'vegetarian'],
    ingredients: [
      { id: '16-1', name: 'baguette', amount: 1, unit: 'whole', notes: 'sliced' },
      { id: '16-2', name: 'tomatoes', amount: 4, unit: 'whole', notes: 'large, diced' },
      { id: '16-3', name: 'fresh basil', amount: 0.25, unit: 'cup', notes: 'chopped' },
      { id: '16-4', name: 'garlic', amount: 3, unit: 'whole', notes: 'cloves, minced' },
      { id: '16-5', name: 'extra virgin olive oil', amount: 0.25, unit: 'cup' },
      { id: '16-6', name: 'balsamic vinegar', amount: 1, unit: 'tbsp' },
      { id: '16-7', name: 'salt and pepper', amount: 0, unit: 'pinch', notes: 'to taste' },
    ],
    steps: [
      { id: '16-s1', stepNumber: 1, instruction: 'Preheat oven to 400°F. Arrange baguette slices on baking sheet.' },
      { id: '16-s2', stepNumber: 2, instruction: 'Brush bread with olive oil. Toast for 5-7 minutes until golden.', duration: 7 },
      { id: '16-s3', stepNumber: 3, instruction: 'In a bowl, combine tomatoes, basil, garlic, remaining olive oil, and balsamic vinegar.' },
      { id: '16-s4', stepNumber: 4, instruction: 'Season with salt and pepper. Let marinate for 10 minutes.', duration: 10 },
      { id: '16-s5', stepNumber: 5, instruction: 'Spoon tomato mixture onto toasted bread. Serve immediately.' },
    ],
    nutrition: {
      calories: 140,
      protein: 4,
      carbs: 18,
      fat: 6,
      fiber: 2,
      sugar: 3,
    },
  },
  {
    id: '17',
    name: 'Spinach Artichoke Dip',
    description: 'Creamy, cheesy dip with spinach and artichokes. Perfect party appetizer.',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800',
    categoryId: '5',
    prepTime: 10,
    cookTime: 25,
    totalTime: 35,
    servings: 10,
    difficulty: 'easy',
    featured: true,
    rating: 4.9,
    reviewCount: 567,
    tags: ['appetizer', 'dip', 'vegetarian', 'party'],
    ingredients: [
      { id: '17-1', name: 'frozen spinach', amount: 10, unit: 'oz', notes: 'thawed and drained' },
      { id: '17-2', name: 'artichoke hearts', amount: 14, unit: 'oz', notes: 'canned, chopped' },
      { id: '17-3', name: 'cream cheese', amount: 8, unit: 'oz', notes: 'softened' },
      { id: '17-4', name: 'sour cream', amount: 0.5, unit: 'cup' },
      { id: '17-5', name: 'mayonnaise', amount: 0.5, unit: 'cup' },
      { id: '17-6', name: 'parmesan cheese', amount: 0.5, unit: 'cup', notes: 'grated' },
      { id: '17-7', name: 'mozzarella cheese', amount: 1, unit: 'cup', notes: 'shredded' },
      { id: '17-8', name: 'garlic', amount: 3, unit: 'whole', notes: 'cloves, minced' },
    ],
    steps: [
      { id: '17-s1', stepNumber: 1, instruction: 'Preheat oven to 350°F.' },
      { id: '17-s2', stepNumber: 2, instruction: 'In a large bowl, mix cream cheese, sour cream, and mayonnaise until smooth.' },
      { id: '17-s3', stepNumber: 3, instruction: 'Stir in spinach, artichokes, parmesan, half the mozzarella, and garlic.' },
      { id: '17-s4', stepNumber: 4, instruction: 'Transfer to baking dish. Top with remaining mozzarella.' },
      { id: '17-s5', stepNumber: 5, instruction: 'Bake for 20-25 minutes until bubbly and golden.', duration: 25 },
      { id: '17-s6', stepNumber: 6, instruction: 'Serve hot with tortilla chips, crackers, or bread.' },
    ],
    nutrition: {
      calories: 240,
      protein: 8,
      carbs: 6,
      fat: 21,
      fiber: 2,
      sugar: 2,
    },
  },

  // SALADS (2 recipes)
  {
    id: '18',
    name: 'Greek Salad',
    description: 'Fresh vegetables, feta cheese, and kalamata olives with herb vinaigrette.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    categoryId: '6',
    prepTime: 15,
    cookTime: 0,
    totalTime: 15,
    servings: 6,
    difficulty: 'easy',
    rating: 4.6,
    reviewCount: 189,
    tags: ['salad', 'greek', 'vegetarian', 'healthy'],
    ingredients: [
      { id: '18-1', name: 'romaine lettuce', amount: 1, unit: 'whole', notes: 'head, chopped' },
      { id: '18-2', name: 'cucumbers', amount: 2, unit: 'whole', notes: 'diced' },
      { id: '18-3', name: 'cherry tomatoes', amount: 2, unit: 'cup', notes: 'halved' },
      { id: '18-4', name: 'red onion', amount: 0.5, unit: 'whole', notes: 'thinly sliced' },
      { id: '18-5', name: 'kalamata olives', amount: 0.5, unit: 'cup' },
      { id: '18-6', name: 'feta cheese', amount: 1, unit: 'cup', notes: 'crumbled' },
      { id: '18-7', name: 'extra virgin olive oil', amount: 0.25, unit: 'cup' },
      { id: '18-8', name: 'red wine vinegar', amount: 2, unit: 'tbsp' },
      { id: '18-9', name: 'dried oregano', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { id: '18-s1', stepNumber: 1, instruction: 'In a large bowl, combine lettuce, cucumbers, tomatoes, onion, and olives.' },
      { id: '18-s2', stepNumber: 2, instruction: 'In a small bowl, whisk olive oil, vinegar, and oregano.' },
      { id: '18-s3', stepNumber: 3, instruction: 'Pour dressing over salad and toss gently.' },
      { id: '18-s4', stepNumber: 4, instruction: 'Top with feta cheese and serve immediately.' },
    ],
    nutrition: {
      calories: 180,
      protein: 5,
      carbs: 8,
      fat: 15,
      fiber: 2,
      sugar: 4,
    },
  },
  {
    id: '19',
    name: 'Caprese Salad',
    description: 'Simple Italian salad with fresh mozzarella, tomatoes, and basil. Summer on a plate.',
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800',
    categoryId: '6',
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    servings: 4,
    difficulty: 'easy',
    rating: 4.8,
    reviewCount: 312,
    tags: ['salad', 'italian', 'vegetarian', 'quick'],
    ingredients: [
      { id: '19-1', name: 'fresh mozzarella', amount: 16, unit: 'oz', notes: 'sliced' },
      { id: '19-2', name: 'ripe tomatoes', amount: 4, unit: 'whole', notes: 'large, sliced' },
      { id: '19-3', name: 'fresh basil leaves', amount: 20, unit: 'whole' },
      { id: '19-4', name: 'extra virgin olive oil', amount: 0.25, unit: 'cup' },
      { id: '19-5', name: 'balsamic glaze', amount: 2, unit: 'tbsp' },
      { id: '19-6', name: 'sea salt', amount: 0, unit: 'pinch', notes: 'to taste' },
      { id: '19-7', name: 'black pepper', amount: 0, unit: 'pinch', notes: 'freshly ground' },
    ],
    steps: [
      { id: '19-s1', stepNumber: 1, instruction: 'Arrange alternating slices of tomato and mozzarella on a platter.' },
      { id: '19-s2', stepNumber: 2, instruction: 'Tuck basil leaves between slices.' },
      { id: '19-s3', stepNumber: 3, instruction: 'Drizzle with olive oil and balsamic glaze.' },
      { id: '19-s4', stepNumber: 4, instruction: 'Season with sea salt and freshly ground black pepper. Serve at room temperature.' },
    ],
    nutrition: {
      calories: 280,
      protein: 14,
      carbs: 8,
      fat: 22,
      fiber: 2,
      sugar: 5,
    },
  },

  // SOUP (1 recipe)
  {
    id: '20',
    name: 'Tomato Basil Soup',
    description: 'Creamy tomato soup with fresh basil. Comfort in a bowl, perfect with grilled cheese.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    categoryId: '7',
    prepTime: 10,
    cookTime: 30,
    totalTime: 40,
    servings: 6,
    difficulty: 'easy',
    rating: 4.8,
    reviewCount: 423,
    tags: ['soup', 'vegetarian', 'comfort-food'],
    ingredients: [
      { id: '20-1', name: 'olive oil', amount: 2, unit: 'tbsp' },
      { id: '20-2', name: 'onion', amount: 1, unit: 'whole', notes: 'large, diced' },
      { id: '20-3', name: 'garlic', amount: 4, unit: 'whole', notes: 'cloves, minced' },
      { id: '20-4', name: 'crushed tomatoes', amount: 28, unit: 'oz', notes: 'canned' },
      { id: '20-5', name: 'vegetable broth', amount: 2, unit: 'cup' },
      { id: '20-6', name: 'fresh basil', amount: 0.5, unit: 'cup', notes: 'chopped' },
      { id: '20-7', name: 'heavy cream', amount: 0.5, unit: 'cup' },
      { id: '20-8', name: 'sugar', amount: 1, unit: 'tsp' },
      { id: '20-9', name: 'salt and pepper', amount: 0, unit: 'pinch', notes: 'to taste' },
    ],
    steps: [
      { id: '20-s1', stepNumber: 1, instruction: 'Heat olive oil in large pot over medium heat. Sauté onion until softened, about 5 minutes.', duration: 5 },
      { id: '20-s2', stepNumber: 2, instruction: 'Add garlic and cook for 1 minute until fragrant.' },
      { id: '20-s3', stepNumber: 3, instruction: 'Add crushed tomatoes, vegetable broth, and sugar. Bring to a boil.' },
      { id: '20-s4', stepNumber: 4, instruction: 'Reduce heat and simmer for 20 minutes.', duration: 20 },
      { id: '20-s5', stepNumber: 5, instruction: 'Stir in basil and heavy cream. Use immersion blender to puree until smooth.' },
      { id: '20-s6', stepNumber: 6, instruction: 'Season with salt and pepper. Serve hot with crusty bread.' },
    ],
    nutrition: {
      calories: 160,
      protein: 3,
      carbs: 14,
      fat: 11,
      fiber: 3,
      sugar: 8,
    },
  },
];

// Service Functions
export async function getCategories(): Promise<Category[]> {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 300));
  return [...MOCK_CATEGORIES];
}

export async function getRecipes(categoryId?: string): Promise<Recipe[]> {
  await new Promise(resolve => setTimeout(resolve, 500));

  let recipes = [...MOCK_RECIPES];
  if (categoryId) {
    recipes = recipes.filter(recipe => recipe.categoryId === categoryId);
  }
  return recipes;
}

export async function getRecipeById(id: string): Promise<Recipe | null> {
  await new Promise(resolve => setTimeout(resolve, 300));

  const recipe = MOCK_RECIPES.find(r => r.id === id);
  return recipe || null;
}

export async function getFeaturedRecipes(): Promise<Recipe[]> {
  await new Promise(resolve => setTimeout(resolve, 400));

  return MOCK_RECIPES.filter(r => r.featured === true);
}

export async function searchRecipes(query: string): Promise<Recipe[]> {
  await new Promise(resolve => setTimeout(resolve, 500));

  const lowerQuery = query.toLowerCase();
  return MOCK_RECIPES.filter(recipe =>
    recipe.name.toLowerCase().includes(lowerQuery) ||
    recipe.description.toLowerCase().includes(lowerQuery) ||
    recipe.tags?.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
