/**
 * Supabase Types Template
 *
 * Generates TypeScript type definitions
 */

import type { CodeGenContext } from '@mobigen/connectors-core/types';

export function supabaseTypesTemplate(ctx: CodeGenContext): string {
  return `/**
 * Supabase Type Definitions
 *
 * Auto-generated by Mobigen Supabase Connector
 * TypeScript types for Supabase services
 */

import type {
  User,
  Session,
  Provider,
  AuthError,
  PostgrestError,
  StorageError,
} from '@supabase/supabase-js';

// Re-export commonly used types from Supabase
export type {
  User,
  Session,
  Provider,
  AuthError,
  PostgrestError,
  StorageError,
};

/**
 * Authentication result type
 */
export interface AuthResult {
  user: User | null;
  session: Session | null;
  error?: AuthError | null;
}

/**
 * Database query result type
 */
export interface QueryResult<T> {
  data: T[] | null;
  error: PostgrestError | null;
  count?: number | null;
}

/**
 * Single record query result type
 */
export interface SingleResult<T> {
  data: T | null;
  error: PostgrestError | null;
}

/**
 * Storage operation result type
 */
export interface StorageResult {
  data: any | null;
  error: StorageError | null;
}

/**
 * OAuth provider types
 */
export type OAuthProvider =
  | 'google'
  | 'apple'
  | 'github'
  | 'gitlab'
  | 'bitbucket'
  | 'azure'
  | 'facebook'
  | 'discord'
  | 'twitter'
  | 'spotify'
  | 'linkedin'
  | 'slack'
  | 'twitch'
  | 'notion'
  | 'zoom';

/**
 * Auth state change event types
 */
export type AuthChangeEvent =
  | 'SIGNED_IN'
  | 'SIGNED_OUT'
  | 'TOKEN_REFRESHED'
  | 'USER_UPDATED'
  | 'PASSWORD_RECOVERY';

/**
 * Realtime event types
 */
export type RealtimeEvent = 'INSERT' | 'UPDATE' | 'DELETE';

/**
 * Pagination options
 */
export interface PaginationOptions {
  page?: number;
  pageSize?: number;
  orderBy?: string;
  ascending?: boolean;
  filter?: Record<string, any>;
}

/**
 * Pagination result
 */
export interface PaginationResult<T> {
  data: T[] | null;
  count: number | null;
  error: PostgrestError | null;
}

/**
 * File upload options
 */
export interface FileUploadOptions {
  cacheControl?: string;
  contentType?: string;
  upsert?: boolean;
}

/**
 * File object in storage
 */
export interface StorageFile {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
  metadata: {
    size: number;
    mimetype: string;
    cacheControl?: string;
    [key: string]: any;
  };
}

/**
 * Storage bucket
 */
export interface StorageBucket {
  id: string;
  name: string;
  public: boolean;
  created_at: string;
  updated_at: string;
  file_size_limit?: number;
  allowed_mime_types?: string[];
}

/**
 * Realtime subscription callbacks
 */
export interface RealtimeCallbacks<T> {
  onInsert?: (record: T) => void;
  onUpdate?: (record: T) => void;
  onDelete?: (record: T) => void;
}

/**
 * User metadata type
 */
export interface UserMetadata {
  [key: string]: any;
}

/**
 * Edge function invoke options
 */
export interface EdgeFunctionOptions {
  headers?: Record<string, string>;
  method?: 'POST' | 'GET' | 'PUT' | 'DELETE' | 'PATCH';
}

/**
 * Database table base type
 * Extend this for your own table types
 *
 * @example
 * ```typescript
 * interface Product extends TableRecord {
 *   name: string;
 *   price: number;
 *   category: string;
 * }
 * ```
 */
export interface TableRecord {
  id: string;
  created_at?: string;
  updated_at?: string;
}

/**
 * Filter operator types
 */
export type FilterOperator =
  | 'eq'
  | 'neq'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'like'
  | 'ilike'
  | 'is'
  | 'in'
  | 'contains'
  | 'containedBy'
  | 'overlaps';

/**
 * Query filter
 */
export interface QueryFilter {
  column: string;
  operator: FilterOperator;
  value: any;
}

/**
 * Order by options
 */
export interface OrderByOptions {
  column: string;
  ascending?: boolean;
  nullsFirst?: boolean;
}

// ============================================================================
// PROJECT-SPECIFIC TYPES
// ============================================================================
// Add your custom database table types below

/**
 * Example: User profile type
 *
 * @example
 * ```typescript
 * export interface UserProfile extends TableRecord {
 *   user_id: string;
 *   username: string;
 *   avatar_url?: string;
 *   bio?: string;
 * }
 * ```
 */

/**
 * Example: Product type
 *
 * @example
 * ```typescript
 * export interface Product extends TableRecord {
 *   name: string;
 *   description?: string;
 *   price: number;
 *   category: string;
 *   image_url?: string;
 *   stock: number;
 * }
 * ```
 */

// Add more custom types here as needed for your project
`;
}
