/**
 * Supabase Storage Service Template
 *
 * Generates storage/file upload functions
 */

import type { CodeGenContext } from '@mobigen/connectors-core/types';

export function supabaseStorageTemplate(ctx: CodeGenContext): string {
  return `/**
 * Supabase Storage Service
 *
 * Auto-generated by Mobigen Supabase Connector
 * Provides file upload, download, and management capabilities
 */

import { supabase } from './supabase-client';
import type { StorageError } from '@supabase/supabase-js';

/**
 * Upload a file to a storage bucket
 *
 * @param bucket - Name of the storage bucket
 * @param path - Path where the file should be stored
 * @param file - File data (Blob, File, or base64 string)
 * @param options - Upload options
 * @returns Upload result with file path
 *
 * @example
 * ```typescript
 * // Upload image from React Native
 * const photo = {
 *   uri: 'file:///path/to/photo.jpg',
 *   type: 'image/jpeg',
 *   name: 'photo.jpg',
 * };
 *
 * const { data, error } = await upload('avatars', \`users/\${userId}/avatar.jpg\`, photo);
 * if (data) {
 *   console.log('Uploaded to:', data.path);
 * }
 * ```
 */
export async function upload(
  bucket: string,
  path: string,
  file: any,
  options: {
    cacheControl?: string;
    contentType?: string;
    upsert?: boolean;
  } = {}
): Promise<{ data: { path: string } | null; error: StorageError | null }> {
  try {
    let fileData: Blob | ArrayBuffer;

    // Handle different file types
    if (typeof file === 'string') {
      // Base64 string
      const base64Data = file.includes('base64,') ? file.split('base64,')[1] : file;
      const binaryString = atob(base64Data);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      fileData = bytes.buffer;
    } else if (file.uri) {
      // React Native asset
      const response = await fetch(file.uri);
      fileData = await response.blob();
    } else {
      // Blob or File
      fileData = file;
    }

    const { data, error } = await supabase.storage
      .from(bucket)
      .upload(path, fileData, {
        cacheControl: options.cacheControl || '3600',
        contentType: options.contentType || file.type || 'application/octet-stream',
        upsert: options.upsert || false,
      });

    return { data, error };
  } catch (err: any) {
    return {
      data: null,
      error: {
        message: err.message || 'Upload failed',
        name: 'UploadError',
      } as StorageError,
    };
  }
}

/**
 * Download a file from storage
 *
 * @param bucket - Name of the storage bucket
 * @param path - Path to the file
 * @returns File blob
 *
 * @example
 * ```typescript
 * const { data: blob, error } = await download('avatars', 'users/123/avatar.jpg');
 * if (blob) {
 *   // Use the blob (e.g., display image)
 * }
 * ```
 */
export async function download(
  bucket: string,
  path: string
): Promise<{ data: Blob | null; error: StorageError | null }> {
  const { data, error } = await supabase.storage.from(bucket).download(path);

  return { data, error };
}

/**
 * Get public URL for a file
 *
 * @param bucket - Name of the storage bucket
 * @param path - Path to the file
 * @returns Public URL
 *
 * @example
 * ```typescript
 * const url = getPublicUrl('avatars', 'users/123/avatar.jpg');
 * // Use url in <Image source={{ uri: url }} />
 * ```
 */
export function getPublicUrl(bucket: string, path: string): string {
  const { data } = supabase.storage.from(bucket).getPublicUrl(path);
  return data.publicUrl;
}

/**
 * Create a signed URL for private files
 *
 * @param bucket - Name of the storage bucket
 * @param path - Path to the file
 * @param expiresIn - Expiry time in seconds (default: 1 hour)
 * @returns Signed URL
 *
 * @example
 * ```typescript
 * const { data, error } = await createSignedUrl('private-docs', 'contracts/agreement.pdf', 3600);
 * if (data) {
 *   console.log('Signed URL:', data.signedUrl);
 * }
 * ```
 */
export async function createSignedUrl(
  bucket: string,
  path: string,
  expiresIn: number = 3600
): Promise<{ data: { signedUrl: string } | null; error: StorageError | null }> {
  const { data, error } = await supabase.storage
    .from(bucket)
    .createSignedUrl(path, expiresIn);

  return { data, error };
}

/**
 * List files in a bucket
 *
 * @param bucket - Name of the storage bucket
 * @param path - Path to list (optional)
 * @param options - List options
 * @returns List of files
 *
 * @example
 * ```typescript
 * const { data: files, error } = await listFiles('avatars', 'users/123');
 * files?.forEach(file => console.log(file.name));
 * ```
 */
export async function listFiles(
  bucket: string,
  path: string = '',
  options: {
    limit?: number;
    offset?: number;
    sortBy?: { column: string; order: 'asc' | 'desc' };
  } = {}
): Promise<{
  data: Array<{ name: string; id: string; updated_at: string; created_at: string; metadata: any }> | null;
  error: StorageError | null;
}> {
  const { data, error } = await supabase.storage.from(bucket).list(path, options);

  return { data, error };
}

/**
 * Delete a file from storage
 *
 * @param bucket - Name of the storage bucket
 * @param paths - Path(s) to delete
 * @returns Deletion result
 *
 * @example
 * ```typescript
 * // Delete single file
 * await deleteFile('avatars', 'users/123/old-avatar.jpg');
 *
 * // Delete multiple files
 * await deleteFile('avatars', ['users/123/photo1.jpg', 'users/123/photo2.jpg']);
 * ```
 */
export async function deleteFile(
  bucket: string,
  paths: string | string[]
): Promise<{ data: any | null; error: StorageError | null }> {
  const pathArray = Array.isArray(paths) ? paths : [paths];

  const { data, error } = await supabase.storage.from(bucket).remove(pathArray);

  return { data, error };
}

/**
 * Move a file within storage
 *
 * @param bucket - Name of the storage bucket
 * @param fromPath - Current path of the file
 * @param toPath - New path for the file
 * @returns Move result
 *
 * @example
 * ```typescript
 * await moveFile('avatars', 'temp/upload.jpg', 'users/123/avatar.jpg');
 * ```
 */
export async function moveFile(
  bucket: string,
  fromPath: string,
  toPath: string
): Promise<{ data: any | null; error: StorageError | null }> {
  const { data, error } = await supabase.storage.from(bucket).move(fromPath, toPath);

  return { data, error };
}

/**
 * Copy a file within storage
 *
 * @param bucket - Name of the storage bucket
 * @param fromPath - Source path
 * @param toPath - Destination path
 * @returns Copy result
 *
 * @example
 * ```typescript
 * await copyFile('avatars', 'users/123/avatar.jpg', 'backups/avatar-backup.jpg');
 * ```
 */
export async function copyFile(
  bucket: string,
  fromPath: string,
  toPath: string
): Promise<{ data: any | null; error: StorageError | null }> {
  const { data, error } = await supabase.storage.from(bucket).copy(fromPath, toPath);

  return { data, error };
}

/**
 * Create a new storage bucket
 *
 * @param bucketName - Name of the bucket to create
 * @param options - Bucket options
 * @returns Creation result
 *
 * @example
 * ```typescript
 * await createBucket('user-uploads', { public: true });
 * ```
 */
export async function createBucket(
  bucketName: string,
  options: {
    public?: boolean;
    fileSizeLimit?: number;
    allowedMimeTypes?: string[];
  } = {}
): Promise<{ data: any | null; error: StorageError | null }> {
  const { data, error } = await supabase.storage.createBucket(bucketName, {
    public: options.public || false,
    fileSizeLimit: options.fileSizeLimit,
    allowedMimeTypes: options.allowedMimeTypes,
  });

  return { data, error };
}

/**
 * Delete a storage bucket
 *
 * @param bucketName - Name of the bucket to delete
 * @returns Deletion result
 */
export async function deleteBucket(
  bucketName: string
): Promise<{ data: any | null; error: StorageError | null }> {
  const { data, error } = await supabase.storage.deleteBucket(bucketName);

  return { data, error };
}

/**
 * Get bucket details
 *
 * @param bucketName - Name of the bucket
 * @returns Bucket information
 */
export async function getBucket(
  bucketName: string
): Promise<{
  data: { id: string; name: string; public: boolean; created_at: string } | null;
  error: StorageError | null;
}> {
  const { data, error } = await supabase.storage.getBucket(bucketName);

  return { data, error };
}

/**
 * List all buckets
 *
 * @returns List of buckets
 */
export async function listBuckets(): Promise<{
  data: Array<{ id: string; name: string; public: boolean; created_at: string }> | null;
  error: StorageError | null;
}> {
  const { data, error } = await supabase.storage.listBuckets();

  return { data, error };
}
`;
}
