/**
 * Supabase Client Template
 *
 * Generates the Supabase client initialization code
 */

import type { CodeGenContext } from '@mobigen/connectors-core/types';

export function supabaseClientTemplate(ctx: CodeGenContext): string {
  return `/**
 * Supabase Client Configuration
 *
 * Auto-generated by Mobigen Supabase Connector
 * Project: ${ctx.projectConfig.appName}
 * Generated: ${new Date().toISOString()}
 */

import 'react-native-url-polyfill/auto';
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Supabase project configuration
const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL || '${ctx.env.SUPABASE_URL}';
const SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '${ctx.env.SUPABASE_ANON_KEY}';

/**
 * Supabase client instance
 *
 * Configured with AsyncStorage for session persistence in React Native.
 * This ensures users stay logged in between app sessions.
 */
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: AsyncStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});

/**
 * Get the current Supabase URL
 */
export function getSupabaseUrl(): string {
  return SUPABASE_URL;
}

/**
 * Check if Supabase is properly configured
 */
export function isSupabaseConfigured(): boolean {
  return !!SUPABASE_URL && !!SUPABASE_ANON_KEY;
}
`;
}
