/**
 * Supabase Auth Service Template
 *
 * Generates authentication service functions
 */

import type { CodeGenContext } from '@mobigen/connectors-core/types';

export function supabaseAuthTemplate(ctx: CodeGenContext): string {
  return `/**
 * Supabase Authentication Service
 *
 * Auto-generated by Mobigen Supabase Connector
 * Provides authentication functions for email/password, OAuth, and magic links
 */

import { supabase } from './supabase-client';
import type {
  AuthError,
  Session,
  User,
  AuthTokenResponsePassword,
  SignInWithPasswordCredentials,
  SignUpWithPasswordCredentials,
  Provider,
} from '@supabase/supabase-js';

/**
 * Sign in with email and password
 */
export async function signInWithPassword(
  credentials: SignInWithPasswordCredentials
): Promise<{ data: { user: User | null; session: Session | null }; error: AuthError | null }> {
  return await supabase.auth.signInWithPassword(credentials);
}

/**
 * Sign up with email and password
 */
export async function signUp(
  credentials: SignUpWithPasswordCredentials
): Promise<{ data: { user: User | null; session: Session | null }; error: AuthError | null }> {
  return await supabase.auth.signUp(credentials);
}

/**
 * Sign in with OAuth provider (Google, Apple, GitHub, etc.)
 *
 * @param provider - OAuth provider name
 * @param redirectTo - Optional redirect URL after authentication
 *
 * @example
 * ```typescript
 * await signInWithOAuth('google');
 * await signInWithOAuth('apple', 'myapp://auth/callback');
 * ```
 */
export async function signInWithOAuth(
  provider: Provider,
  redirectTo?: string
): Promise<{ data: { url: string }; error: AuthError | null }> {
  return await supabase.auth.signInWithOAuth({
    provider,
    options: {
      redirectTo: redirectTo || '${ctx.projectConfig.bundleIdIos}://auth/callback',
      skipBrowserRedirect: true, // For React Native
    },
  });
}

/**
 * Sign in with magic link (passwordless email login)
 *
 * @param email - User's email address
 * @param redirectTo - Optional redirect URL after clicking the link
 *
 * @example
 * ```typescript
 * await signInWithMagicLink('user@example.com');
 * ```
 */
export async function signInWithMagicLink(
  email: string,
  redirectTo?: string
): Promise<{ data: object; error: AuthError | null }> {
  return await supabase.auth.signInWithOtp({
    email,
    options: {
      emailRedirectTo: redirectTo || '${ctx.projectConfig.bundleIdIos}://auth/callback',
    },
  });
}

/**
 * Sign out the current user
 */
export async function signOut(): Promise<{ error: AuthError | null }> {
  return await supabase.auth.signOut();
}

/**
 * Get the current session
 */
export async function getSession(): Promise<{
  data: { session: Session | null };
  error: AuthError | null;
}> {
  return await supabase.auth.getSession();
}

/**
 * Get the current user
 */
export async function getUser(): Promise<{
  data: { user: User | null };
  error: AuthError | null;
}> {
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();

  return { data: { user }, error };
}

/**
 * Update user metadata
 */
export async function updateUser(attributes: {
  email?: string;
  password?: string;
  data?: object;
}): Promise<{ data: { user: User | null }; error: AuthError | null }> {
  return await supabase.auth.updateUser(attributes);
}

/**
 * Reset password for email
 */
export async function resetPasswordForEmail(
  email: string,
  redirectTo?: string
): Promise<{ data: object; error: AuthError | null }> {
  return await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: redirectTo || '${ctx.projectConfig.bundleIdIos}://auth/reset-password',
  });
}

/**
 * Verify OTP (for magic link or phone auth)
 */
export async function verifyOtp(params: {
  email?: string;
  phone?: string;
  token: string;
  type: 'email' | 'sms' | 'signup' | 'invite' | 'magiclink' | 'recovery';
}): Promise<{ data: { user: User | null; session: Session | null }; error: AuthError | null }> {
  return await supabase.auth.verifyOtp(params);
}

/**
 * Subscribe to auth state changes
 *
 * @param callback - Function to call when auth state changes
 * @returns Unsubscribe function
 *
 * @example
 * ```typescript
 * const unsubscribe = onAuthStateChange((event, session) => {
 *   console.log('Auth state changed:', event, session);
 * });
 *
 * // Later: unsubscribe()
 * ```
 */
export function onAuthStateChange(
  callback: (event: string, session: Session | null) => void
): { unsubscribe: () => void } {
  const { data } = supabase.auth.onAuthStateChange(callback);
  return {
    unsubscribe: () => data.subscription.unsubscribe(),
  };
}
`;
}
