/**
 * Supabase Auth Hooks Template
 *
 * Generates React hooks for authentication
 */

import type { CodeGenContext } from '@mobigen/connectors-core/types';

export function useSupabaseAuthTemplate(ctx: CodeGenContext): string {
  return `/**
 * Supabase Authentication Hooks
 *
 * Auto-generated by Mobigen Supabase Connector
 * React hooks for managing authentication state and operations
 */

import { useState, useEffect, useCallback } from 'react';
import type { Session, User, Provider } from '@supabase/supabase-js';
import * as AuthService from '../services/supabase-auth';

/**
 * Hook for managing authentication state
 *
 * Automatically syncs with Supabase auth state changes.
 *
 * @example
 * ```typescript
 * function MyComponent() {
 *   const { user, session, loading } = useSupabaseAuth();
 *
 *   if (loading) return <Loading />;
 *   if (!user) return <Login />;
 *
 *   return <Dashboard user={user} />;
 * }
 * ```
 */
export function useSupabaseAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Get initial session
    AuthService.getSession()
      .then(({ data, error }) => {
        if (!error && data.session) {
          setSession(data.session);
          setUser(data.session.user);
        }
        setLoading(false);
      });

    // Listen for auth changes
    const { unsubscribe } = AuthService.onAuthStateChange((event, session) => {
      setSession(session);
      setUser(session?.user ?? null);
      setLoading(false);
    });

    return () => {
      unsubscribe();
    };
  }, []);

  return {
    user,
    session,
    loading,
    isAuthenticated: !!user,
  };
}

/**
 * Hook for sign in with email/password
 *
 * @example
 * ```typescript
 * function LoginForm() {
 *   const { signIn, loading, error } = useSupabaseSignIn();
 *
 *   const handleSubmit = async (email: string, password: string) => {
 *     const { user } = await signIn(email, password);
 *     if (user) {
 *       // Success - navigate to home
 *     }
 *   };
 *
 *   return (
 *     <form>
 *       {error && <Error message={error} />}
 *       <button disabled={loading}>Sign In</button>
 *     </form>
 *   );
 * }
 * ```
 */
export function useSupabaseSignIn() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const signIn = useCallback(async (email: string, password: string) => {
    setLoading(true);
    setError(null);

    try {
      const { data, error } = await AuthService.signInWithPassword({
        email,
        password,
      });

      if (error) {
        setError(error.message);
        return { user: null, session: null };
      }

      return { user: data.user, session: data.session };
    } catch (err: any) {
      setError(err.message || 'Sign in failed');
      return { user: null, session: null };
    } finally {
      setLoading(false);
    }
  }, []);

  const signInWithOAuth = useCallback(async (provider: Provider) => {
    setLoading(true);
    setError(null);

    try {
      const { data, error } = await AuthService.signInWithOAuth(provider);

      if (error) {
        setError(error.message);
        return { url: null };
      }

      // Open the OAuth URL in browser
      // You'll need to handle the redirect back to the app
      return { url: data.url };
    } catch (err: any) {
      setError(err.message || 'OAuth sign in failed');
      return { url: null };
    } finally {
      setLoading(false);
    }
  }, []);

  const signInWithMagicLink = useCallback(async (email: string) => {
    setLoading(true);
    setError(null);

    try {
      const { error } = await AuthService.signInWithMagicLink(email);

      if (error) {
        setError(error.message);
        return { success: false };
      }

      return { success: true };
    } catch (err: any) {
      setError(err.message || 'Magic link failed');
      return { success: false };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    signIn,
    signInWithOAuth,
    signInWithMagicLink,
    loading,
    error,
  };
}

/**
 * Hook for sign up with email/password
 *
 * @example
 * ```typescript
 * function SignUpForm() {
 *   const { signUp, loading, error } = useSupabaseSignUp();
 *
 *   const handleSubmit = async (email: string, password: string) => {
 *     const { user } = await signUp(email, password);
 *     if (user) {
 *       // Success - show confirmation message
 *     }
 *   };
 *
 *   return <form>{/* ... */}</form>;
 * }
 * ```
 */
export function useSupabaseSignUp() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const signUp = useCallback(async (email: string, password: string, metadata?: object) => {
    setLoading(true);
    setError(null);

    try {
      const { data, error } = await AuthService.signUp({
        email,
        password,
        options: {
          data: metadata,
        },
      });

      if (error) {
        setError(error.message);
        return { user: null, session: null };
      }

      return { user: data.user, session: data.session };
    } catch (err: any) {
      setError(err.message || 'Sign up failed');
      return { user: null, session: null };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    signUp,
    loading,
    error,
  };
}

/**
 * Hook for sign out
 *
 * @example
 * ```typescript
 * function ProfileMenu() {
 *   const { signOut, loading } = useSupabaseSignOut();
 *
 *   return (
 *     <button onClick={signOut} disabled={loading}>
 *       Sign Out
 *     </button>
 *   );
 * }
 * ```
 */
export function useSupabaseSignOut() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const signOut = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const { error } = await AuthService.signOut();

      if (error) {
        setError(error.message);
        return { success: false };
      }

      return { success: true };
    } catch (err: any) {
      setError(err.message || 'Sign out failed');
      return { success: false };
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    signOut,
    loading,
    error,
  };
}
`;
}
