import type { Listing, Seller } from '@/types';

const MOCK_SELLERS: Seller[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/150?img=1',
    rating: 4.8,
    reviewCount: 45,
    joinedDate: new Date('2023-01-15'),
    activeListings: 8,
  },
  {
    id: '2',
    name: 'Mike Chen',
    avatar: 'https://i.pravatar.cc/150?img=12',
    rating: 4.9,
    reviewCount: 78,
    joinedDate: new Date('2022-08-20'),
    activeListings: 12,
  },
  {
    id: '3',
    name: 'Emily Davis',
    avatar: 'https://i.pravatar.cc/150?img=5',
    rating: 4.6,
    reviewCount: 32,
    joinedDate: new Date('2023-03-10'),
    activeListings: 5,
  },
  {
    id: '4',
    name: 'John Smith',
    avatar: 'https://i.pravatar.cc/150?img=8',
    rating: 4.7,
    reviewCount: 56,
    joinedDate: new Date('2022-11-05'),
    activeListings: 9,
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'iPhone 14 Pro - Space Black',
    description: 'Like new iPhone 14 Pro with 256GB storage. Comes with original box and charger. No scratches or damage.',
    price: 799,
    images: [
      'https://picsum.photos/seed/iphone1/600/600',
      'https://picsum.photos/seed/iphone2/600/600',
      'https://picsum.photos/seed/iphone3/600/600',
    ],
    categoryId: 'electronics',
    category: 'Electronics',
    condition: 'like-new',
    location: 'San Francisco, CA',
    sellerId: '1',
    seller: MOCK_SELLERS[0],
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2024-12-20'),
  },
  {
    id: '2',
    title: 'Mid-Century Modern Sofa',
    description: 'Beautiful teal velvet sofa in excellent condition. 3-seater, very comfortable. Moving sale!',
    price: 450,
    images: [
      'https://picsum.photos/seed/sofa1/600/600',
      'https://picsum.photos/seed/sofa2/600/600',
    ],
    categoryId: 'furniture',
    category: 'Furniture',
    condition: 'good',
    location: 'Oakland, CA',
    sellerId: '2',
    seller: MOCK_SELLERS[1],
    createdAt: new Date('2024-12-19'),
    updatedAt: new Date('2024-12-19'),
  },
  {
    id: '3',
    title: 'Mountain Bike - Trek X-Caliber',
    description: 'Trek X-Caliber 29er mountain bike. Well maintained, new tires and brakes. Great for trails!',
    price: 650,
    images: [
      'https://picsum.photos/seed/bike1/600/600',
      'https://picsum.photos/seed/bike2/600/600',
      'https://picsum.photos/seed/bike3/600/600',
    ],
    categoryId: 'sports',
    category: 'Sports & Outdoors',
    condition: 'good',
    location: 'Berkeley, CA',
    sellerId: '3',
    seller: MOCK_SELLERS[2],
    createdAt: new Date('2024-12-18'),
    updatedAt: new Date('2024-12-18'),
  },
  {
    id: '4',
    title: 'Nike Air Jordan 1 High - Size 10',
    description: 'Brand new, never worn Air Jordan 1 High in University Blue colorway. Size 10 mens. Original box included.',
    price: 180,
    images: [
      'https://picsum.photos/seed/shoes1/600/600',
      'https://picsum.photos/seed/shoes2/600/600',
    ],
    categoryId: 'fashion',
    category: 'Fashion & Apparel',
    condition: 'new',
    location: 'San Jose, CA',
    sellerId: '4',
    seller: MOCK_SELLERS[3],
    createdAt: new Date('2024-12-17'),
    updatedAt: new Date('2024-12-17'),
  },
  {
    id: '5',
    title: 'Canon EOS R6 Camera Body',
    description: 'Professional mirrorless camera in excellent condition. Low shutter count (5,000). Comes with battery and charger.',
    price: 1899,
    images: [
      'https://picsum.photos/seed/camera1/600/600',
      'https://picsum.photos/seed/camera2/600/600',
      'https://picsum.photos/seed/camera3/600/600',
    ],
    categoryId: 'electronics',
    category: 'Electronics',
    condition: 'like-new',
    location: 'Palo Alto, CA',
    sellerId: '1',
    seller: MOCK_SELLERS[0],
    createdAt: new Date('2024-12-16'),
    updatedAt: new Date('2024-12-16'),
  },
  {
    id: '6',
    title: 'Vintage Leather Armchair',
    description: 'Beautiful vintage brown leather armchair. Some patina adds character. Very comfortable!',
    price: 275,
    images: [
      'https://picsum.photos/seed/chair1/600/600',
      'https://picsum.photos/seed/chair2/600/600',
    ],
    categoryId: 'furniture',
    category: 'Furniture',
    condition: 'good',
    location: 'San Francisco, CA',
    sellerId: '2',
    seller: MOCK_SELLERS[1],
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: '7',
    title: 'KitchenAid Stand Mixer - Red',
    description: 'Classic red KitchenAid stand mixer. Barely used, works perfectly. Includes whisk, beater, and dough hook.',
    price: 220,
    images: [
      'https://picsum.photos/seed/mixer1/600/600',
      'https://picsum.photos/seed/mixer2/600/600',
    ],
    categoryId: 'home',
    category: 'Home & Garden',
    condition: 'like-new',
    location: 'Mountain View, CA',
    sellerId: '3',
    seller: MOCK_SELLERS[2],
    createdAt: new Date('2024-12-14'),
    updatedAt: new Date('2024-12-14'),
  },
  {
    id: '8',
    title: 'PlayStation 5 Console + Controller',
    description: 'PS5 disc version with extra controller. Excellent condition, all cables included. Selling due to upgrade.',
    price: 450,
    images: [
      'https://picsum.photos/seed/ps5-1/600/600',
      'https://picsum.photos/seed/ps5-2/600/600',
    ],
    categoryId: 'electronics',
    category: 'Electronics',
    condition: 'good',
    location: 'Santa Clara, CA',
    sellerId: '4',
    seller: MOCK_SELLERS[3],
    createdAt: new Date('2024-12-13'),
    updatedAt: new Date('2024-12-13'),
  },
  {
    id: '9',
    title: 'Patagonia Down Jacket - Mens Large',
    description: 'Patagonia down puffer jacket in navy blue. Very warm, perfect for winter. Gently used.',
    price: 120,
    images: [
      'https://picsum.photos/seed/jacket1/600/600',
      'https://picsum.photos/seed/jacket2/600/600',
    ],
    categoryId: 'fashion',
    category: 'Fashion & Apparel',
    condition: 'good',
    location: 'Fremont, CA',
    sellerId: '1',
    seller: MOCK_SELLERS[0],
    createdAt: new Date('2024-12-12'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: '10',
    title: 'Weber Gas Grill - 3 Burner',
    description: 'Weber Spirit II E-310 gas grill. Works great, well maintained. Includes cover and propane tank.',
    price: 380,
    images: [
      'https://picsum.photos/seed/grill1/600/600',
      'https://picsum.photos/seed/grill2/600/600',
    ],
    categoryId: 'home',
    category: 'Home & Garden',
    condition: 'good',
    location: 'Sunnyvale, CA',
    sellerId: '2',
    seller: MOCK_SELLERS[1],
    createdAt: new Date('2024-12-11'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: '11',
    title: 'iPad Pro 12.9" (2021) - 256GB',
    description: 'Space Gray iPad Pro with Magic Keyboard and Apple Pencil 2. Like new condition, barely used.',
    price: 899,
    images: [
      'https://picsum.photos/seed/ipad1/600/600',
      'https://picsum.photos/seed/ipad2/600/600',
      'https://picsum.photos/seed/ipad3/600/600',
    ],
    categoryId: 'electronics',
    category: 'Electronics',
    condition: 'like-new',
    location: 'Cupertino, CA',
    sellerId: '3',
    seller: MOCK_SELLERS[2],
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: '12',
    title: 'Dining Table Set - 6 Chairs',
    description: 'Solid wood dining table with 6 matching chairs. Seats 8 comfortably. Great condition!',
    price: 550,
    images: [
      'https://picsum.photos/seed/table1/600/600',
      'https://picsum.photos/seed/table2/600/600',
    ],
    categoryId: 'furniture',
    category: 'Furniture',
    condition: 'good',
    location: 'Redwood City, CA',
    sellerId: '4',
    seller: MOCK_SELLERS[3],
    createdAt: new Date('2024-12-09'),
    updatedAt: new Date('2024-12-09'),
  },
  {
    id: '13',
    title: 'Dyson V11 Cordless Vacuum',
    description: 'Powerful cordless vacuum with multiple attachments. Great for hardwood and carpet. Excellent condition.',
    price: 299,
    images: [
      'https://picsum.photos/seed/vacuum1/600/600',
      'https://picsum.photos/seed/vacuum2/600/600',
    ],
    categoryId: 'home',
    category: 'Home & Garden',
    condition: 'like-new',
    location: 'Menlo Park, CA',
    sellerId: '1',
    seller: MOCK_SELLERS[0],
    createdAt: new Date('2024-12-08'),
    updatedAt: new Date('2024-12-08'),
  },
  {
    id: '14',
    title: 'Road Bike - Specialized Allez',
    description: 'Specialized Allez road bike, 54cm frame. Carbon fork, Shimano 105 components. Great for commuting or fitness.',
    price: 750,
    images: [
      'https://picsum.photos/seed/roadbike1/600/600',
      'https://picsum.photos/seed/roadbike2/600/600',
    ],
    categoryId: 'sports',
    category: 'Sports & Outdoors',
    condition: 'good',
    location: 'San Mateo, CA',
    sellerId: '2',
    seller: MOCK_SELLERS[1],
    createdAt: new Date('2024-12-07'),
    updatedAt: new Date('2024-12-07'),
  },
  {
    id: '15',
    title: 'Lululemon Yoga Mat + Bag',
    description: 'Reversible yoga mat with carrying bag. 5mm thickness, excellent grip. Gently used.',
    price: 55,
    images: [
      'https://picsum.photos/seed/yogamat1/600/600',
    ],
    categoryId: 'sports',
    category: 'Sports & Outdoors',
    condition: 'good',
    location: 'Los Altos, CA',
    sellerId: '3',
    seller: MOCK_SELLERS[2],
    createdAt: new Date('2024-12-06'),
    updatedAt: new Date('2024-12-06'),
  },
  {
    id: '16',
    title: 'MacBook Air M2 - 16GB RAM',
    description: 'Latest MacBook Air with M2 chip, 16GB RAM, 512GB SSD. Space Gray. AppleCare+ included.',
    price: 1199,
    images: [
      'https://picsum.photos/seed/macbook1/600/600',
      'https://picsum.photos/seed/macbook2/600/600',
    ],
    categoryId: 'electronics',
    category: 'Electronics',
    condition: 'like-new',
    location: 'San Francisco, CA',
    sellerId: '4',
    seller: MOCK_SELLERS[3],
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: '17',
    title: 'Designer Handbag - Michael Kors',
    description: 'Authentic Michael Kors tote bag in brown leather. Excellent condition, barely used. Original dust bag included.',
    price: 165,
    images: [
      'https://picsum.photos/seed/bag1/600/600',
      'https://picsum.photos/seed/bag2/600/600',
    ],
    categoryId: 'fashion',
    category: 'Fashion & Apparel',
    condition: 'like-new',
    location: 'Palo Alto, CA',
    sellerId: '1',
    seller: MOCK_SELLERS[0],
    createdAt: new Date('2024-12-04'),
    updatedAt: new Date('2024-12-04'),
  },
  {
    id: '18',
    title: 'Office Chair - Herman Miller Aeron',
    description: 'Classic Herman Miller Aeron chair, size B. Fully adjustable, excellent lumbar support. Like new!',
    price: 650,
    images: [
      'https://picsum.photos/seed/officechair1/600/600',
      'https://picsum.photos/seed/officechair2/600/600',
    ],
    categoryId: 'furniture',
    category: 'Furniture',
    condition: 'like-new',
    location: 'Mountain View, CA',
    sellerId: '2',
    seller: MOCK_SELLERS[1],
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: '19',
    title: 'Electric Skateboard - Boosted Board',
    description: 'Boosted Board Stealth electric skateboard. 14 miles range, top speed 24mph. Well maintained.',
    price: 699,
    images: [
      'https://picsum.photos/seed/eskate1/600/600',
      'https://picsum.photos/seed/eskate2/600/600',
    ],
    categoryId: 'sports',
    category: 'Sports & Outdoors',
    condition: 'good',
    location: 'San Jose, CA',
    sellerId: '3',
    seller: MOCK_SELLERS[2],
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: '20',
    title: 'Instant Pot Duo - 6 Quart',
    description: 'Multi-functional pressure cooker. 7-in-1 appliance. Barely used, works perfectly. Great for meal prep!',
    price: 65,
    images: [
      'https://picsum.photos/seed/instantpot1/600/600',
    ],
    categoryId: 'home',
    category: 'Home & Garden',
    condition: 'like-new',
    location: 'Fremont, CA',
    sellerId: '4',
    seller: MOCK_SELLERS[3],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
];

export async function fetchListings(categoryId?: string): Promise<Listing[]> {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (categoryId) {
    return MOCK_LISTINGS.filter((listing) => listing.categoryId === categoryId);
  }

  return MOCK_LISTINGS;
}

export async function fetchListing(id: string): Promise<Listing | null> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return MOCK_LISTINGS.find((listing) => listing.id === id) || null;
}

export async function searchListings(query: string): Promise<Listing[]> {
  await new Promise((resolve) => setTimeout(resolve, 400));

  const lowerQuery = query.toLowerCase();
  return MOCK_LISTINGS.filter(
    (listing) =>
      listing.title.toLowerCase().includes(lowerQuery) ||
      listing.description.toLowerCase().includes(lowerQuery) ||
      listing.category.toLowerCase().includes(lowerQuery)
  );
}

export async function createListing(listing: Omit<Listing, 'id' | 'createdAt' | 'updatedAt'>): Promise<Listing> {
  await new Promise((resolve) => setTimeout(resolve, 600));

  const newListing: Listing = {
    ...listing,
    id: String(Date.now()),
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  return newListing;
}
